### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse
  commentId: T:Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse
  id: GetResourceStorageConfigResponse
  parent: Microsoft.Azure.Management.BackupServices.Models
  children:
  - Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.#ctor
  - Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.ResourceId
  - Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.StorageDetails
  langs:
  - csharp
  - vb
  name: GetResourceStorageConfigResponse
  nameWithType: GetResourceStorageConfigResponse
  fullName: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/AzureBackup/BackupServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: GetResourceStorageConfigResponse
    path: src/ResourceManagement/AzureBackup/BackupServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.BackupServicesManagement
  namespace: Microsoft.Azure.Management.BackupServices.Models
  summary: "\nThe definition of a get resource storage config response.\n"
  example: []
  syntax:
    content: 'public class GetResourceStorageConfigResponse : AzureOperationResponse'
    content.vb: >-
      Public Class GetResourceStorageConfigResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.ResourceId
  commentId: P:Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.ResourceId
  id: ResourceId
  parent: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse
  langs:
  - csharp
  - vb
  name: ResourceId
  nameWithType: GetResourceStorageConfigResponse.ResourceId
  fullName: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.ResourceId
  type: Property
  source:
    remote:
      path: src/ResourceManagement/AzureBackup/BackupServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ResourceId
    path: src/ResourceManagement/AzureBackup/BackupServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.BackupServicesManagement
  namespace: Microsoft.Azure.Management.BackupServices.Models
  summary: "\nOptional. Gets or sets the resource ID.\n"
  example: []
  syntax:
    content: public long ResourceId { get; set; }
    content.vb: Public Property ResourceId As Long
    parameters: []
    return:
      type: System.Int64
  overload: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.ResourceId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.StorageDetails
  commentId: P:Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.StorageDetails
  id: StorageDetails
  parent: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse
  langs:
  - csharp
  - vb
  name: StorageDetails
  nameWithType: GetResourceStorageConfigResponse.StorageDetails
  fullName: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.StorageDetails
  type: Property
  source:
    remote:
      path: src/ResourceManagement/AzureBackup/BackupServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: StorageDetails
    path: src/ResourceManagement/AzureBackup/BackupServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.BackupServicesManagement
  namespace: Microsoft.Azure.Management.BackupServices.Models
  summary: "\nOptional. The resource storage details.\n"
  example: []
  syntax:
    content: public StorageDetails StorageDetails { get; set; }
    content.vb: Public Property StorageDetails As StorageDetails
    parameters: []
    return:
      type: Microsoft.Azure.Management.BackupServices.Models.StorageDetails
  overload: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.StorageDetails*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.#ctor
  commentId: M:Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse
  langs:
  - csharp
  - vb
  name: GetResourceStorageConfigResponse()
  nameWithType: GetResourceStorageConfigResponse.GetResourceStorageConfigResponse()
  fullName: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.GetResourceStorageConfigResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/AzureBackup/BackupServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/AzureBackup/BackupServicesManagement/Generated/Models/GetResourceStorageConfigResponse.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.BackupServicesManagement
  namespace: Microsoft.Azure.Management.BackupServices.Models
  summary: "\nInitializes a new instance of the GetResourceStorageConfigResponse\nclass.\n"
  example: []
  syntax:
    content: public GetResourceStorageConfigResponse()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.BackupServices.Models
  commentId: N:Microsoft.Azure.Management.BackupServices.Models
  isExternal: false
  name: Microsoft.Azure.Management.BackupServices.Models
  nameWithType: Microsoft.Azure.Management.BackupServices.Models
  fullName: Microsoft.Azure.Management.BackupServices.Models
- uid: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.ResourceId*
  commentId: Overload:Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.ResourceId
  isExternal: false
  name: ResourceId
  nameWithType: GetResourceStorageConfigResponse.ResourceId
  fullName: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.ResourceId
- uid: System.Int64
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.StorageDetails*
  commentId: Overload:Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.StorageDetails
  isExternal: false
  name: StorageDetails
  nameWithType: GetResourceStorageConfigResponse.StorageDetails
  fullName: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.StorageDetails
- uid: Microsoft.Azure.Management.BackupServices.Models.StorageDetails
  commentId: T:Microsoft.Azure.Management.BackupServices.Models.StorageDetails
  parent: Microsoft.Azure.Management.BackupServices.Models
  isExternal: false
  name: StorageDetails
  nameWithType: StorageDetails
  fullName: Microsoft.Azure.Management.BackupServices.Models.StorageDetails
- uid: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.#ctor*
  commentId: Overload:Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.#ctor
  isExternal: false
  name: GetResourceStorageConfigResponse
  nameWithType: GetResourceStorageConfigResponse.GetResourceStorageConfigResponse
  fullName: Microsoft.Azure.Management.BackupServices.Models.GetResourceStorageConfigResponse.GetResourceStorageConfigResponse
