### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.ResourceManager.Models.Deployment
  commentId: T:Microsoft.Azure.Management.ResourceManager.Models.Deployment
  id: Deployment
  parent: Microsoft.Azure.Management.ResourceManager.Models
  children:
  - Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor
  - Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor(Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties)
  - Microsoft.Azure.Management.ResourceManager.Models.Deployment.Properties
  - Microsoft.Azure.Management.ResourceManager.Models.Deployment.Validate
  langs:
  - csharp
  - vb
  name: Deployment
  nameWithType: Deployment
  fullName: Microsoft.Azure.Management.ResourceManager.Models.Deployment
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Deployment
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nDeployment operation parameters.\n"
  example: []
  syntax:
    content: public class Deployment
    content.vb: Public Class Deployment
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.ResourceManager.Models.Deployment
  langs:
  - csharp
  - vb
  name: Deployment()
  nameWithType: Deployment.Deployment()
  fullName: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Deployment()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nInitializes a new instance of the Deployment class.\n"
  example: []
  syntax:
    content: public Deployment()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor(Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties)
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor(Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties)
  id: '#ctor(Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties)'
  parent: Microsoft.Azure.Management.ResourceManager.Models.Deployment
  langs:
  - csharp
  - vb
  name: Deployment(DeploymentProperties)
  nameWithType: Deployment.Deployment(DeploymentProperties)
  fullName: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Deployment(Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
    startLine: 26
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nInitializes a new instance of the Deployment class.\n"
  example: []
  syntax:
    content: public Deployment(DeploymentProperties properties = null)
    content.vb: Public Sub New(properties As DeploymentProperties = Nothing)
    parameters:
    - id: properties
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties
      description: The deployment properties.
  overload: Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Properties
  commentId: P:Microsoft.Azure.Management.ResourceManager.Models.Deployment.Properties
  id: Properties
  parent: Microsoft.Azure.Management.ResourceManager.Models.Deployment
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: Deployment.Properties
  fullName: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Properties
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nGets or sets the deployment properties.\n"
  example: []
  syntax:
    content: >-
      [JsonProperty(PropertyName = "properties")]

      public DeploymentProperties Properties { get; set; }
    content.vb: >-
      <JsonProperty(PropertyName:="properties")>

      Public Property Properties As DeploymentProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties
  overload: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Properties*
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor
    arguments: []
    namedArguments:
    - name: PropertyName
      type: System.String
      value: properties
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Validate
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.Deployment.Validate
  id: Validate
  parent: Microsoft.Azure.Management.ResourceManager.Models.Deployment
  langs:
  - csharp
  - vb
  name: Validate()
  nameWithType: Deployment.Validate()
  fullName: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/Deployment.cs
    startLine: 43
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nValidate the object.\n"
  example: []
  syntax:
    content: public virtual void Validate()
    content.vb: Public Overridable Sub Validate
  overload: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Validate*
  exceptions:
  - type: Microsoft.Rest.ValidationException
    commentId: T:Microsoft.Rest.ValidationException
    description: "\nThrown if validation fails\n"
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.Azure.Management.ResourceManager.Models
  commentId: N:Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: Microsoft.Azure.Management.ResourceManager.Models
  nameWithType: Microsoft.Azure.Management.ResourceManager.Models
  fullName: Microsoft.Azure.Management.ResourceManager.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor*
  commentId: Overload:Microsoft.Azure.Management.ResourceManager.Models.Deployment.#ctor
  isExternal: false
  name: Deployment
  nameWithType: Deployment.Deployment
  fullName: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Deployment
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties
  commentId: T:Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties
  parent: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: DeploymentProperties
  nameWithType: DeploymentProperties
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentProperties
- uid: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Properties*
  commentId: Overload:Microsoft.Azure.Management.ResourceManager.Models.Deployment.Properties
  isExternal: false
  name: Properties
  nameWithType: Deployment.Properties
  fullName: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Properties
- uid: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Validate*
  commentId: Overload:Microsoft.Azure.Management.ResourceManager.Models.Deployment.Validate
  isExternal: false
  name: Validate
  nameWithType: Deployment.Validate
  fullName: Microsoft.Azure.Management.ResourceManager.Models.Deployment.Validate
- uid: Microsoft.Rest.ValidationException
  commentId: T:Microsoft.Rest.ValidationException
