### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  commentId: T:Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  id: DeploymentMode
  parent: Microsoft.Azure.Management.ResourceManager.Models
  children:
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode.Complete
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode.Incremental
  langs:
  - csharp
  - vb
  name: DeploymentMode
  nameWithType: DeploymentMode
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentMode.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DeploymentMode
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentMode.cs
    startLine: 14
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nDefines values for DeploymentMode.\n"
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof (StringEnumConverter))]

      public enum DeploymentMode
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum DeploymentMode
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode.Incremental
  commentId: F:Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode.Incremental
  id: Incremental
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  langs:
  - csharp
  - vb
  name: Incremental
  nameWithType: DeploymentMode.Incremental
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode.Incremental
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentMode.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Incremental
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentMode.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  syntax:
    content: >-
      [EnumMember(Value = "Incremental")]

      Incremental = 0
    content.vb: >-
      <EnumMember(Value:="Incremental")>

      Incremental = 0
    return:
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Incremental
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode.Complete
  commentId: F:Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode.Complete
  id: Complete
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  langs:
  - csharp
  - vb
  name: Complete
  nameWithType: DeploymentMode.Complete
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode.Complete
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentMode.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Complete
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentMode.cs
    startLine: 19
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  syntax:
    content: >-
      [EnumMember(Value = "Complete")]

      Complete = 1
    content.vb: >-
      <EnumMember(Value:="Complete")>

      Complete = 1
    return:
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Complete
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.ResourceManager.Models
  commentId: N:Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: Microsoft.Azure.Management.ResourceManager.Models
  nameWithType: Microsoft.Azure.Management.ResourceManager.Models
  fullName: Microsoft.Azure.Management.ResourceManager.Models
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  commentId: T:Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  parent: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: DeploymentMode
  nameWithType: DeploymentMode
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
