environment:
  access_token:
    secure: JWSy9tPo2eoTYpPQplvokf4IiVk6onNBbWwAs6nNWWyQ2JaO+MRAg/QzbJnTjpUm

install:
  - cinst docfx
  - git checkout master

before_build:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "vscopbld@microsoft.com"
  - git config --global user.name "OpenPublishBuild"
  - ps: scripts\UpdateSrcRepo.ps1

build_script:
  - ps: scripts\build.ps1

test:
  assemblies:

on_success:
  - git add .
  - git diff --quiet --exit-code --cached || git commit -m "Update Reference Content" && git push -u origin master
  - appveyor AddMessage "Document Updated"
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
