items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol
  id: ApplicationGatewaySslProtocol
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv10
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv11
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv12
  langs:
  - csharp
  - vb
  name: ApplicationGatewaySslProtocol
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewaySslProtocol.cs
      branch: d5a285f62aaca7c28a3903c582d06203f788270c
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewaySslProtocol
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewaySslProtocol.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.1-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nDefines values for ApplicationGatewaySslProtocol.\n"
  example: []
  syntax:
    content: public class ApplicationGatewaySslProtocol
    content.vb: Public Class ApplicationGatewaySslProtocol
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv10
  commentId: F:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv10
  id: TLSv10
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol
  langs:
  - csharp
  - vb
  name: TLSv10
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv10
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewaySslProtocol.cs
      branch: d5a285f62aaca7c28a3903c582d06203f788270c
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: TLSv10
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewaySslProtocol.cs
    startLine: 19
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.1-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  syntax:
    content: public const string TLSv10 = "TLSv1_0"
    content.vb: Public Const TLSv10 As String = "TLSv1_0"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv11
  commentId: F:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv11
  id: TLSv11
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol
  langs:
  - csharp
  - vb
  name: TLSv11
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv11
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewaySslProtocol.cs
      branch: d5a285f62aaca7c28a3903c582d06203f788270c
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: TLSv11
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewaySslProtocol.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.1-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  syntax:
    content: public const string TLSv11 = "TLSv1_1"
    content.vb: Public Const TLSv11 As String = "TLSv1_1"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv12
  commentId: F:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv12
  id: TLSv12
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol
  langs:
  - csharp
  - vb
  name: TLSv12
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslProtocol.TLSv12
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewaySslProtocol.cs
      branch: d5a285f62aaca7c28a3903c582d06203f788270c
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: TLSv12
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewaySslProtocol.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.1-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  syntax:
    content: public const string TLSv12 = "TLSv1_2"
    content.vb: Public Const TLSv12 As String = "TLSv1_2"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
