items:
- uid: Microsoft.Azure.Management.Compute.Models.SshConfiguration
  commentId: T:Microsoft.Azure.Management.Compute.Models.SshConfiguration
  id: SshConfiguration
  parent: Microsoft.Azure.Management.Compute.Models
  children:
  - Microsoft.Azure.Management.Compute.Models.SshConfiguration.#ctor
  - Microsoft.Azure.Management.Compute.Models.SshConfiguration.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.SshPublicKey})
  - Microsoft.Azure.Management.Compute.Models.SshConfiguration.PublicKeys
  langs:
  - csharp
  - vb
  name: SshConfiguration
  fullName: Microsoft.Azure.Management.Compute.Models.SshConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/SshConfiguration.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: SshConfiguration
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/SshConfiguration.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nSSH configuration for Linux based VMs running on Azure\n"
  example: []
  syntax:
    content: public class SshConfiguration
    content.vb: Public Class SshConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Compute.Models.SshConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Compute.Models.SshConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Compute.Models.SshConfiguration
  langs:
  - csharp
  - vb
  name: SshConfiguration()
  fullName: Microsoft.Azure.Management.Compute.Models.SshConfiguration.SshConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/SshConfiguration.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/SshConfiguration.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nInitializes a new instance of the SshConfiguration class.\n"
  example: []
  syntax:
    content: public SshConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.SshConfiguration.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.SshPublicKey})
  commentId: M:Microsoft.Azure.Management.Compute.Models.SshConfiguration.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.SshPublicKey})
  id: '#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.SshPublicKey})'
  parent: Microsoft.Azure.Management.Compute.Models.SshConfiguration
  langs:
  - csharp
  - vb
  name: SshConfiguration(IList<SshPublicKey>)
  fullName: Microsoft.Azure.Management.Compute.Models.SshConfiguration.SshConfiguration(System.Collections.Generic.IList<Microsoft.Azure.Management.Compute.Models.SshPublicKey>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/SshConfiguration.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/SshConfiguration.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nInitializes a new instance of the SshConfiguration class.\n"
  example: []
  syntax:
    content: public SshConfiguration(IList<SshPublicKey> publicKeys = null)
    content.vb: Public Sub New(publicKeys As IList(Of SshPublicKey) = Nothing)
    parameters:
    - id: publicKeys
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.SshPublicKey}
      description: >-
        the list of SSH public keys used to

        authenticate with linux based VMs
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Compute.Models.SshConfiguration.SshConfiguration(System.Collections.Generic.IList(Of Microsoft.Azure.Management.Compute.Models.SshPublicKey))
  name.vb: SshConfiguration(IList(Of SshPublicKey))
- uid: Microsoft.Azure.Management.Compute.Models.SshConfiguration.PublicKeys
  commentId: P:Microsoft.Azure.Management.Compute.Models.SshConfiguration.PublicKeys
  id: PublicKeys
  parent: Microsoft.Azure.Management.Compute.Models.SshConfiguration
  langs:
  - csharp
  - vb
  name: PublicKeys
  fullName: Microsoft.Azure.Management.Compute.Models.SshConfiguration.PublicKeys
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/SshConfiguration.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PublicKeys
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/SshConfiguration.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nGets or sets the list of SSH public keys used to authenticate with\nlinux based VMs\n"
  example: []
  syntax:
    content: public IList<SshPublicKey> PublicKeys { get; set; }
    content.vb: Public Property PublicKeys As IList(Of SshPublicKey)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.SshPublicKey}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: Microsoft.Azure.Management.Compute.Models
  fullName: Microsoft.Azure.Management.Compute.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.SshPublicKey}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<SshPublicKey>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Compute.Models.SshPublicKey>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Compute.Models.SshPublicKey)
  name.vb: IList(Of SshPublicKey)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Compute.Models.SshPublicKey
    name: SshPublicKey
    fullName: Microsoft.Azure.Management.Compute.Models.SshPublicKey
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Compute.Models.SshPublicKey
    name: SshPublicKey
    fullName: Microsoft.Azure.Management.Compute.Models.SshPublicKey
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
