### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile
  commentId: T:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile
  id: HostingEnvironmentProfile
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor(System.String,System.String,System.String)
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Id
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Name
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Type
  langs:
  - csharp
  - vb
  name: HostingEnvironmentProfile
  nameWithType: HostingEnvironmentProfile
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile
  type: Class
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: HostingEnvironmentProfile
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nSpecification for a hostingEnvironment (App Service Environment) to\nuse for this resource\n"
  example: []
  syntax:
    content: public class HostingEnvironmentProfile
    content.vb: Public Class HostingEnvironmentProfile
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor
  commentId: M:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile
  langs:
  - csharp
  - vb
  name: HostingEnvironmentProfile()
  nameWithType: HostingEnvironmentProfile.HostingEnvironmentProfile()
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.HostingEnvironmentProfile()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the HostingEnvironmentProfile class.\n"
  example: []
  syntax:
    content: public HostingEnvironmentProfile()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor(System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile
  langs:
  - csharp
  - vb
  name: HostingEnvironmentProfile(String, String, String)
  nameWithType: HostingEnvironmentProfile.HostingEnvironmentProfile(String, String, String)
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.HostingEnvironmentProfile(System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the HostingEnvironmentProfile class.\n"
  example: []
  syntax:
    content: public HostingEnvironmentProfile(string id = null, string name = null, string type = null)
    content.vb: Public Sub New(id As String = Nothing, name As String = Nothing, type As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: name
      type: System.String
    - id: type
      type: System.String
  overload: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Id
  commentId: P:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Id
  id: Id
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: HostingEnvironmentProfile.Id
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Id
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Id
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nResource id of the hostingEnvironment (App Service Environment)\n"
  example: []
  syntax:
    content: >-
      [JsonProperty(PropertyName = "id")]

      public string Id { get; set; }
    content.vb: >-
      <JsonProperty(PropertyName:="id")>

      Public Property Id As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Id*
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor
    arguments: []
    namedArguments:
    - name: PropertyName
      type: System.String
      value: id
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Name
  commentId: P:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Name
  id: Name
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: HostingEnvironmentProfile.Name
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nName of the hostingEnvironment (App Service Environment) (read\nonly)\n"
  example: []
  syntax:
    content: >-
      [JsonProperty(PropertyName = "name")]

      public string Name { get; set; }
    content.vb: >-
      <JsonProperty(PropertyName:="name")>

      Public Property Name As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Name*
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor
    arguments: []
    namedArguments:
    - name: PropertyName
      type: System.String
      value: name
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Type
  commentId: P:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Type
  id: Type
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: HostingEnvironmentProfile.Type
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Type
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Type
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentProfile.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nResource type of the hostingEnvironment (App Service Environment)\n(read only)\n"
  example: []
  syntax:
    content: >-
      [JsonProperty(PropertyName = "type")]

      public string Type { get; set; }
    content.vb: >-
      <JsonProperty(PropertyName:="type")>

      Public Property Type As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Type*
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor
    arguments: []
    namedArguments:
    - name: PropertyName
      type: System.String
      value: type
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  commentId: N:Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  nameWithType: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor*
  commentId: Overload:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.#ctor
  isExternal: false
  name: HostingEnvironmentProfile
  nameWithType: HostingEnvironmentProfile.HostingEnvironmentProfile
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.HostingEnvironmentProfile
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Id*
  commentId: Overload:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Id
  isExternal: false
  name: Id
  nameWithType: HostingEnvironmentProfile.Id
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Id
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Name*
  commentId: Overload:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Name
  isExternal: false
  name: Name
  nameWithType: HostingEnvironmentProfile.Name
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Name
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Type*
  commentId: Overload:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Type
  isExternal: false
  name: Type
  nameWithType: HostingEnvironmentProfile.Type
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentProfile.Type
