### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection
  id: TokenProviderElementCollection
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.CreateNewElement
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.GetElementKey(ConfigurationElement)
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item(System.String)
  langs:
  - csharp
  - vb
  name: TokenProviderElementCollection
  nameWithType: TokenProviderElementCollection
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: TokenProviderElementCollection
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElementCollection.cs
    startLine: 13
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nRepresents a collection of elements for the token provider.\n"
  example: []
  syntax:
    content: 'public sealed class TokenProviderElementCollection : ConfigurationElementCollection'
    content.vb: >-
      Public NotInheritable Class TokenProviderElementCollection
          Inherits ConfigurationElementCollection
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.CreateNewElement
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.CreateNewElement
  id: CreateNewElement
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection
  langs:
  - csharp
  - vb
  name: CreateNewElement()
  nameWithType: TokenProviderElementCollection.CreateNewElement()
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.CreateNewElement()
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CreateNewElement
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElementCollection.cs
    startLine: 22
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nWhen overridden in a derived class, creates a new <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: protected override ConfigurationElement CreateNewElement()
    content.vb: Protected Overrides Function CreateNewElement As ConfigurationElement
    return:
      type: ConfigurationElement
      description: "\nA new <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.CreateNewElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.GetElementKey(ConfigurationElement)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.GetElementKey(ConfigurationElement)
  id: GetElementKey(ConfigurationElement)
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection
  langs:
  - csharp
  - vb
  name: GetElementKey(ConfigurationElement)
  nameWithType: TokenProviderElementCollection.GetElementKey(ConfigurationElement)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: GetElementKey
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElementCollection.cs
    startLine: 32
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the element key for a specified configuration element when overridden in a derived class.\n"
  example: []
  syntax:
    content: protected override object GetElementKey(ConfigurationElement element)
    content.vb: Protected Overrides Function GetElementKey(element As ConfigurationElement) As Object
    parameters:
    - id: element
      type: ConfigurationElement
      description: The <xref href="System.Configuration.ConfigurationElement" data-throw-if-not-resolved="false"></xref> to return the key for.
    return:
      type: System.Object
      description: "\nAn <xref href=\"System.Object\" data-throw-if-not-resolved=\"false\"></xref> that acts as the key for the specified <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.GetElementKey*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item(System.String)
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item(System.String)
  id: Item(System.String)
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection
  langs:
  - csharp
  - vb
  name: Item[String]
  nameWithType: TokenProviderElementCollection.Item[String]
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item[System.String]
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: this[]
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElementCollection.cs
    startLine: 51
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets an item in the collection.\n"
  example: []
  syntax:
    content: public TokenProviderElement this[string name] { get; }
    content.vb: Public ReadOnly Property Item(name As String) As TokenProviderElement
    parameters:
    - id: name
      type: System.String
      description: The name of the item.
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
      description: "\nAn item in the collection.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item*
  nameWithType.vb: TokenProviderElementCollection.Item(String)
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
  fullName.vb: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item(System.String)
  name.vb: Item(String)
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Configuration.ConfigurationElement
  commentId: T:System.Configuration.ConfigurationElement
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.CreateNewElement*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.CreateNewElement
  isExternal: false
  name: CreateNewElement
  nameWithType: TokenProviderElementCollection.CreateNewElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.CreateNewElement
- uid: ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: ConfigurationElement
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.GetElementKey*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.GetElementKey
  isExternal: false
  name: GetElementKey
  nameWithType: TokenProviderElementCollection.GetElementKey
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.GetElementKey
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item
  isExternal: false
  name: Item
  nameWithType: TokenProviderElementCollection.Item
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElementCollection.Item
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: TokenProviderElement
  nameWithType: TokenProviderElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
