### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  id: StsUriElementCollection
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.#ctor
  - Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.Addresses
  - Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.CreateNewElement
  - Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.ElementName
  - Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.GetElementKey(ConfigurationElement)
  - Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.IsElementName(System.String)
  langs:
  - csharp
  - vb
  name: StsUriElementCollection
  nameWithType: StsUriElementCollection
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: StsUriElementCollection
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
    startLine: 14
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nRepresents a URI element collection for the Security Token Service.\n"
  example: []
  syntax:
    content: 'public sealed class StsUriElementCollection : ConfigurationElementCollection'
    content.vb: >-
      Public NotInheritable Class StsUriElementCollection
          Inherits ConfigurationElementCollection
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.#ctor
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  langs:
  - csharp
  - vb
  name: StsUriElementCollection()
  nameWithType: StsUriElementCollection.StsUriElementCollection()
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.StsUriElementCollection()
  type: Constructor
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: .ctor
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
    startLine: 26
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nInitializes a new instance of the <xref href=\"Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public StsUriElementCollection()
    content.vb: Public Sub New
  overload: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.ElementName
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.ElementName
  id: ElementName
  parent: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  langs:
  - csharp
  - vb
  name: ElementName
  nameWithType: StsUriElementCollection.ElementName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.ElementName
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: ElementName
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
    startLine: 35
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the name used to identify this collection of elements in the configuration file when overridden in a derived class.\n"
  example: []
  syntax:
    content: protected override string ElementName { get; }
    content.vb: Protected Overrides ReadOnly Property ElementName As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.ElementName*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.IsElementName(System.String)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.IsElementName(System.String)
  id: IsElementName(System.String)
  parent: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  langs:
  - csharp
  - vb
  name: IsElementName(String)
  nameWithType: StsUriElementCollection.IsElementName(String)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.IsElementName(System.String)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: IsElementName
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
    startLine: 47
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nIndicates whether the specified <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref> exists in the <xref href=\"System.Configuration.ConfigurationElementCollection\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: protected override bool IsElementName(string elementName)
    content.vb: Protected Overrides Function IsElementName(elementName As String) As Boolean
    parameters:
    - id: elementName
      type: System.String
      description: The name of the element to verify.
    return:
      type: System.Boolean
      description: "\ntrue if the element exists in the collection; otherwise, false. The default is false.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.IsElementName*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.CreateNewElement
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.CreateNewElement
  id: CreateNewElement
  parent: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  langs:
  - csharp
  - vb
  name: CreateNewElement()
  nameWithType: StsUriElementCollection.CreateNewElement()
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.CreateNewElement()
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CreateNewElement
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
    startLine: 58
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nWhen overridden in a derived class, creates a new <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: protected override ConfigurationElement CreateNewElement()
    content.vb: Protected Overrides Function CreateNewElement As ConfigurationElement
    return:
      type: ConfigurationElement
      description: "\nA new <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.CreateNewElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.GetElementKey(ConfigurationElement)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.GetElementKey(ConfigurationElement)
  id: GetElementKey(ConfigurationElement)
  parent: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  langs:
  - csharp
  - vb
  name: GetElementKey(ConfigurationElement)
  nameWithType: StsUriElementCollection.GetElementKey(ConfigurationElement)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: GetElementKey
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
    startLine: 70
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the element key for a specified configuration element when overridden in a derived class.\n"
  example: []
  syntax:
    content: protected override object GetElementKey(ConfigurationElement element)
    content.vb: Protected Overrides Function GetElementKey(element As ConfigurationElement) As Object
    parameters:
    - id: element
      type: ConfigurationElement
      description: The <xref href="System.Configuration.ConfigurationElement" data-throw-if-not-resolved="false"></xref> to return the key for.
    return:
      type: System.Object
      description: "\nAn <xref href=\"System.Object\" data-throw-if-not-resolved=\"false\"></xref> that acts as the key for the specified <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.GetElementKey*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.Addresses
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.Addresses
  id: Addresses
  parent: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  langs:
  - csharp
  - vb
  name: Addresses
  nameWithType: StsUriElementCollection.Addresses
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.Addresses
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Addresses
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElementCollection.cs
    startLine: 82
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the addresses of the element in the collection.\n"
  example: []
  syntax:
    content: public IEnumerable<Uri> Addresses { get; }
    content.vb: Public ReadOnly Property Addresses As IEnumerable(Of Uri)
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{Uri}
      description: "\nThe addresses of the element in the collection.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.Addresses*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: StsUriElementCollection
  nameWithType: StsUriElementCollection
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.#ctor*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.#ctor
  isExternal: false
  name: StsUriElementCollection
  nameWithType: StsUriElementCollection.StsUriElementCollection
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.StsUriElementCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.ElementName*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.ElementName
  isExternal: false
  name: ElementName
  nameWithType: StsUriElementCollection.ElementName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.ElementName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationElement
  commentId: T:System.Configuration.ConfigurationElement
- uid: System.Configuration.ConfigurationElementCollection
  commentId: T:System.Configuration.ConfigurationElementCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.IsElementName*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.IsElementName
  isExternal: false
  name: IsElementName
  nameWithType: StsUriElementCollection.IsElementName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.IsElementName
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.CreateNewElement*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.CreateNewElement
  isExternal: false
  name: CreateNewElement
  nameWithType: StsUriElementCollection.CreateNewElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.CreateNewElement
- uid: ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: ConfigurationElement
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.GetElementKey*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.GetElementKey
  isExternal: false
  name: GetElementKey
  nameWithType: StsUriElementCollection.GetElementKey
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.GetElementKey
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.Addresses*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.Addresses
  isExternal: false
  name: Addresses
  nameWithType: StsUriElementCollection.Addresses
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection.Addresses
- uid: System.Collections.Generic.IEnumerable{Uri}
  commentId: T:System.Collections.Generic.IEnumerable{Uri}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<Uri>
  nameWithType: IEnumerable<Uri>
  fullName: System.Collections.Generic.IEnumerable<Uri>
  nameWithType.vb: IEnumerable(Of Uri)
  fullname.vb: System.Collections.Generic.IEnumerable(Of Uri)
  name.vb: IEnumerable(Of Uri)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Uri
    name: Uri
    nameWithType: Uri
    fullName: Uri
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Uri
    name: Uri
    nameWithType: Uri
    fullName: Uri
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullname.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
