### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement
  id: TransportClientEndpointBehaviorElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.BehaviorType
  - Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CopyFrom(ServiceModelExtensionElement)
  - Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CreateBehavior
  - Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.Properties
  - Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.TokenProvider
  langs:
  - csharp
  - vb
  name: TransportClientEndpointBehaviorElement
  nameWithType: TransportClientEndpointBehaviorElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: TransportClientEndpointBehaviorElement
    path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
    startLine: 13
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nRepresents a configuration element that specifies the behavior of a service or client endpoint for a transport on the Windows Azure Service Bus relay.\n"
  example: []
  syntax:
    content: 'public class TransportClientEndpointBehaviorElement : BehaviorExtensionElement'
    content.vb: >-
      Public Class TransportClientEndpointBehaviorElement
          Inherits BehaviorExtensionElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.TokenProvider
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.TokenProvider
  id: TokenProvider
  parent: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement
  langs:
  - csharp
  - vb
  name: TokenProvider
  nameWithType: TransportClientEndpointBehaviorElement.TokenProvider
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.TokenProvider
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: TokenProvider
    path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
    startLine: 24
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the token provider that is used as a binding parameter.\n"
  example: []
  syntax:
    content: public TokenProviderElement TokenProvider { get; }
    content.vb: Public ReadOnly Property TokenProvider As TokenProviderElement
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
      description: "\nThe token provider used as a binding parameter.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.TokenProvider*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.BehaviorType
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.BehaviorType
  id: BehaviorType
  parent: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement
  langs:
  - csharp
  - vb
  name: BehaviorType
  nameWithType: TransportClientEndpointBehaviorElement.BehaviorType
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.BehaviorType
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: BehaviorType
    path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
    startLine: 37
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the behavior type for the transport client endpoint.\n"
  example: []
  syntax:
    content: public override Type BehaviorType { get; }
    content.vb: Public Overrides ReadOnly Property BehaviorType As Type
    parameters: []
    return:
      type: System.Type
      description: "\nThe behavior type for the transport client endpoint.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.BehaviorType*
  modifiers.csharp:
  - public
  - override
  - get
  modifiers.vb:
  - Public
  - Overrides
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.Properties
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.Properties
  id: Properties
  parent: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: TransportClientEndpointBehaviorElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.Properties
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Properties
    path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
    startLine: 52
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the collection of properties contained in this configuration element.\n"
  example: []
  syntax:
    content: protected override ConfigurationPropertyCollection Properties { get; }
    content.vb: Protected Overrides ReadOnly Property Properties As ConfigurationPropertyCollection
    parameters: []
    return:
      type: ConfigurationPropertyCollection
      description: "\nThe collection of properties contained in this configuration element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.Properties*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CopyFrom(ServiceModelExtensionElement)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CopyFrom(ServiceModelExtensionElement)
  id: CopyFrom(ServiceModelExtensionElement)
  parent: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement
  langs:
  - csharp
  - vb
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: TransportClientEndpointBehaviorElement.CopyFrom(ServiceModelExtensionElement)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CopyFrom
    path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
    startLine: 79
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nCopies the contents of the specified configuration element to this configuration element.\n"
  example: []
  syntax:
    content: public override void CopyFrom(ServiceModelExtensionElement from)
    content.vb: Public Overrides Sub CopyFrom(from As ServiceModelExtensionElement)
    parameters:
    - id: from
      type: ServiceModelExtensionElement
      description: The configuration element to copy the contents from.
  overload: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CopyFrom*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CreateBehavior
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CreateBehavior
  id: CreateBehavior
  parent: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement
  langs:
  - csharp
  - vb
  name: CreateBehavior()
  nameWithType: TransportClientEndpointBehaviorElement.CreateBehavior()
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CreateBehavior()
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CreateBehavior
    path: src/product/clients/Microsoft.Notifications/Configuration/TransportClientEndpointBehaviorElement.cs
    startLine: 93
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nReturns a new <xref href=\"Microsoft.Azure.NotificationHubs.TransportClientEndpointBehavior\" data-throw-if-not-resolved=\"false\"></xref> object with the same settings as this configuration element.\n"
  example: []
  syntax:
    content: protected override object CreateBehavior()
    content.vb: Protected Overrides Function CreateBehavior As Object
    return:
      type: System.Object
      description: "\nA new <xref href=\"Microsoft.Azure.NotificationHubs.TransportClientEndpointBehavior\" data-throw-if-not-resolved=\"false\"></xref> object with the same settings as this configuration element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CreateBehavior*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.TokenProvider*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.TokenProvider
  isExternal: false
  name: TokenProvider
  nameWithType: TransportClientEndpointBehaviorElement.TokenProvider
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.TokenProvider
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: TokenProviderElement
  nameWithType: TokenProviderElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.BehaviorType*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.BehaviorType
  isExternal: false
  name: BehaviorType
  nameWithType: TransportClientEndpointBehaviorElement.BehaviorType
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.BehaviorType
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.Properties*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.Properties
  isExternal: false
  name: Properties
  nameWithType: TransportClientEndpointBehaviorElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.Properties
- uid: ConfigurationPropertyCollection
  isExternal: true
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: ConfigurationPropertyCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CopyFrom*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CopyFrom
  isExternal: false
  name: CopyFrom
  nameWithType: TransportClientEndpointBehaviorElement.CopyFrom
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CopyFrom
- uid: ServiceModelExtensionElement
  isExternal: true
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: ServiceModelExtensionElement
- uid: Microsoft.Azure.NotificationHubs.TransportClientEndpointBehavior
  commentId: T:Microsoft.Azure.NotificationHubs.TransportClientEndpointBehavior
  isExternal: false
  name: TransportClientEndpointBehavior
  nameWithType: TransportClientEndpointBehavior
  fullName: Microsoft.Azure.NotificationHubs.TransportClientEndpointBehavior
- uid: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CreateBehavior*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CreateBehavior
  isExternal: false
  name: CreateBehavior
  nameWithType: TransportClientEndpointBehaviorElement.CreateBehavior
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TransportClientEndpointBehaviorElement.CreateBehavior
