### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  commentId: T:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  id: NamespaceManagerSettings
  parent: Microsoft.Azure.NotificationHubs
  children:
  - Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.#ctor
  - Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.OperationTimeout
  - Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.RetryPolicy
  - Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.TokenProvider
  langs:
  - csharp
  - vb
  name: NamespaceManagerSettings
  nameWithType: NamespaceManagerSettings
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: NamespaceManagerSettings
    path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
    startLine: 15
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nService Bus Namespace client settings. It holds namespace meta data.\n<xref href=\"Microsoft.Azure.NotificationHubs.NamespaceManager\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: public sealed class NamespaceManagerSettings
    content.vb: Public NotInheritable Class NamespaceManagerSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.#ctor
  commentId: M:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  langs:
  - csharp
  - vb
  name: NamespaceManagerSettings()
  nameWithType: NamespaceManagerSettings.NamespaceManagerSettings()
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.NamespaceManagerSettings()
  type: Constructor
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: .ctor
    path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
    startLine: 24
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nInitializes a new instance of the <xref href=\"Microsoft.Azure.NotificationHubs.NamespaceManagerSettings\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public NamespaceManagerSettings()
    content.vb: Public Sub New
  overload: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.OperationTimeout
  commentId: P:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.OperationTimeout
  id: OperationTimeout
  parent: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  langs:
  - csharp
  - vb
  name: OperationTimeout
  nameWithType: NamespaceManagerSettings.OperationTimeout
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.OperationTimeout
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: OperationTimeout
    path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
    startLine: 40
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nGets or sets the operation timeout.\n"
  example: []
  syntax:
    content: public TimeSpan OperationTimeout { get; set; }
    content.vb: Public Property OperationTimeout As TimeSpan
    parameters: []
    return:
      type: System.TimeSpan
      description: "\nThe operation timeout. It sets the timeout period for all of Namespace management operations, such as GetQueue, CreteQueue, etc.\n"
  overload: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.OperationTimeout*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: throws if a null is set - e.g. a nullable TimeSpan.
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: throws when a zero or negative TimeSpan is set.
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.RetryPolicy
  commentId: P:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.RetryPolicy
  id: RetryPolicy
  parent: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  langs:
  - csharp
  - vb
  name: RetryPolicy
  nameWithType: NamespaceManagerSettings.RetryPolicy
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.RetryPolicy
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: RetryPolicy
    path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
    startLine: 66
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nGets or sets the base implementation of the retry mechanism for unreliable actions and transient conditions associated with the namespace manager.\n"
  example: []
  syntax:
    content: public RetryPolicy RetryPolicy { get; set; }
    content.vb: Public Property RetryPolicy As RetryPolicy
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.RetryPolicy
      description: "\nThe base implementation of the retry mechanism for unreliable actions and transient conditions associated with the namespace manager.\n"
  overload: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.RetryPolicy*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.TokenProvider
  commentId: P:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.TokenProvider
  id: TokenProvider
  parent: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  langs:
  - csharp
  - vb
  name: TokenProvider
  nameWithType: NamespaceManagerSettings.TokenProvider
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.TokenProvider
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: TokenProvider
    path: src/product/clients/Microsoft.Notifications/NamespaceManagerSettings.cs
    startLine: 90
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nGets or sets the security token provider.\n"
  example: []
  syntax:
    content: public TokenProvider TokenProvider { get; set; }
    content.vb: Public Property TokenProvider As TokenProvider
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.TokenProvider
      description: "\nThe security token provider.\n"
  overload: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.TokenProvider*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.NotificationHubs.NamespaceManager
  commentId: T:Microsoft.Azure.NotificationHubs.NamespaceManager
  parent: Microsoft.Azure.NotificationHubs
  isExternal: false
  name: NamespaceManager
  nameWithType: NamespaceManager
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManager
- uid: Microsoft.Azure.NotificationHubs
  commentId: N:Microsoft.Azure.NotificationHubs
  isExternal: false
  name: Microsoft.Azure.NotificationHubs
  nameWithType: Microsoft.Azure.NotificationHubs
  fullName: Microsoft.Azure.NotificationHubs
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  commentId: T:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
  parent: Microsoft.Azure.NotificationHubs
  isExternal: false
  name: NamespaceManagerSettings
  nameWithType: NamespaceManagerSettings
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.#ctor*
  commentId: Overload:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.#ctor
  isExternal: false
  name: NamespaceManagerSettings
  nameWithType: NamespaceManagerSettings.NamespaceManagerSettings
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.NamespaceManagerSettings
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.OperationTimeout*
  commentId: Overload:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.OperationTimeout
  isExternal: false
  name: OperationTimeout
  nameWithType: NamespaceManagerSettings.OperationTimeout
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.OperationTimeout
- uid: System.ArgumentNullException
  commentId: T:System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  commentId: T:System.ArgumentOutOfRangeException
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.RetryPolicy*
  commentId: Overload:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.RetryPolicy
  isExternal: false
  name: RetryPolicy
  nameWithType: NamespaceManagerSettings.RetryPolicy
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.RetryPolicy
- uid: Microsoft.Azure.NotificationHubs.RetryPolicy
  commentId: T:Microsoft.Azure.NotificationHubs.RetryPolicy
  parent: Microsoft.Azure.NotificationHubs
  isExternal: false
  name: RetryPolicy
  nameWithType: RetryPolicy
  fullName: Microsoft.Azure.NotificationHubs.RetryPolicy
- uid: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.TokenProvider*
  commentId: Overload:Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.TokenProvider
  isExternal: false
  name: TokenProvider
  nameWithType: NamespaceManagerSettings.TokenProvider
  fullName: Microsoft.Azure.NotificationHubs.NamespaceManagerSettings.TokenProvider
- uid: Microsoft.Azure.NotificationHubs.TokenProvider
  commentId: T:Microsoft.Azure.NotificationHubs.TokenProvider
  parent: Microsoft.Azure.NotificationHubs
  isExternal: false
  name: TokenProvider
  nameWithType: TokenProvider
  fullName: Microsoft.Azure.NotificationHubs.TokenProvider
