### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  id: SharedAccessSignatureElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement)
  - Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Key
  - Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.KeyName
  - Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Properties
  - Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.TokenScope
  langs:
  - csharp
  - vb
  name: SharedAccessSignatureElement
  nameWithType: SharedAccessSignatureElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: SharedAccessSignatureElement
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
    startLine: 11
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nRepresents a shared access signature element.\n"
  example: []
  syntax:
    content: 'public class SharedAccessSignatureElement : ConfigurationElement'
    content.vb: >-
      Public Class SharedAccessSignatureElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.KeyName
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.KeyName
  id: KeyName
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  langs:
  - csharp
  - vb
  name: KeyName
  nameWithType: SharedAccessSignatureElement.KeyName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.KeyName
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: KeyName
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
    startLine: 32
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the shared access key name.\n"
  example: []
  syntax:
    content: public string KeyName { get; set; }
    content.vb: Public Property KeyName As String
    parameters: []
    return:
      type: System.String
      description: "\nThe shared access key name.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.KeyName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Key
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Key
  id: Key
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  langs:
  - csharp
  - vb
  name: Key
  nameWithType: SharedAccessSignatureElement.Key
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Key
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Key
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
    startLine: 47
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the shared access key.\n"
  example: []
  syntax:
    content: public string Key { get; set; }
    content.vb: Public Property Key As String
    parameters: []
    return:
      type: System.String
      description: "\nThe shared access key.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Key*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.TokenScope
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.TokenScope
  id: TokenScope
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  langs:
  - csharp
  - vb
  name: TokenScope
  nameWithType: SharedAccessSignatureElement.TokenScope
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.TokenScope
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: TokenScope
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
    startLine: 62
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the token scope associated with the element.\n"
  example: []
  syntax:
    content: public TokenScope TokenScope { get; set; }
    content.vb: Public Property TokenScope As TokenScope
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.TokenScope
      description: "\nThe token scope associated with the element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.TokenScope*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Properties
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Properties
  id: Properties
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: SharedAccessSignatureElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Properties
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Properties
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
    startLine: 82
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the collection of configuration properties.\n"
  example: []
  syntax:
    content: protected override ConfigurationPropertyCollection Properties { get; }
    content.vb: Protected Overrides ReadOnly Property Properties As ConfigurationPropertyCollection
    parameters: []
    return:
      type: ConfigurationPropertyCollection
      description: "\nThe collection of configuration properties.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Properties*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement)
  id: CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement)
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  langs:
  - csharp
  - vb
  name: CopyFrom(SharedAccessSignatureElement)
  nameWithType: SharedAccessSignatureElement.CopyFrom(SharedAccessSignatureElement)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CopyFrom
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedAccessSignatureElement.cs
    startLine: 103
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nCopies the specified element from this configuration element.\n"
  example: []
  syntax:
    content: public void CopyFrom(SharedAccessSignatureElement source)
    content.vb: Public Sub CopyFrom(source As SharedAccessSignatureElement)
    parameters:
    - id: source
      type: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
      description: The source to copy the contents from.
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.CopyFrom*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.KeyName*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.KeyName
  isExternal: false
  name: KeyName
  nameWithType: SharedAccessSignatureElement.KeyName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.KeyName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Key*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Key
  isExternal: false
  name: Key
  nameWithType: SharedAccessSignatureElement.Key
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Key
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.TokenScope*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.TokenScope
  isExternal: false
  name: TokenScope
  nameWithType: SharedAccessSignatureElement.TokenScope
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.TokenScope
- uid: Microsoft.Azure.NotificationHubs.TokenScope
  commentId: T:Microsoft.Azure.NotificationHubs.TokenScope
  parent: Microsoft.Azure.NotificationHubs
  isExternal: false
  name: TokenScope
  nameWithType: TokenScope
  fullName: Microsoft.Azure.NotificationHubs.TokenScope
- uid: Microsoft.Azure.NotificationHubs
  commentId: N:Microsoft.Azure.NotificationHubs
  isExternal: false
  name: Microsoft.Azure.NotificationHubs
  nameWithType: Microsoft.Azure.NotificationHubs
  fullName: Microsoft.Azure.NotificationHubs
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Properties*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Properties
  isExternal: false
  name: Properties
  nameWithType: SharedAccessSignatureElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.Properties
- uid: ConfigurationPropertyCollection
  isExternal: true
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: ConfigurationPropertyCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.CopyFrom*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.CopyFrom
  isExternal: false
  name: CopyFrom
  nameWithType: SharedAccessSignatureElement.CopyFrom
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement.CopyFrom
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: SharedAccessSignatureElement
  nameWithType: SharedAccessSignatureElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
