### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  id: WindowsElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.WindowsElement)
  - Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Domain
  - Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Password
  - Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Properties
  - Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.StsUris
  - Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UseDefaultCredentials
  - Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UserName
  langs:
  - csharp
  - vb
  name: WindowsElement
  nameWithType: WindowsElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: WindowsElement
    path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
    startLine: 11
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nRepresents the windows element for the configuration of the service bus.\n"
  example: []
  syntax:
    content: 'public class WindowsElement : ConfigurationElement'
    content.vb: >-
      Public Class WindowsElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UseDefaultCredentials
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UseDefaultCredentials
  id: UseDefaultCredentials
  parent: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  langs:
  - csharp
  - vb
  name: UseDefaultCredentials
  nameWithType: WindowsElement.UseDefaultCredentials
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UseDefaultCredentials
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: UseDefaultCredentials
    path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
    startLine: 26
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets a value that indicates whether to use default credentials.\n"
  example: []
  syntax:
    content: public bool UseDefaultCredentials { get; set; }
    content.vb: Public Property UseDefaultCredentials As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: "\ntrue if to use default credentials; otherwise, false.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UseDefaultCredentials*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UserName
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UserName
  id: UserName
  parent: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  langs:
  - csharp
  - vb
  name: UserName
  nameWithType: WindowsElement.UserName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UserName
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: UserName
    path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
    startLine: 40
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the username.\n"
  example: []
  syntax:
    content: public string UserName { get; set; }
    content.vb: Public Property UserName As String
    parameters: []
    return:
      type: System.String
      description: "\nThe username.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UserName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Password
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Password
  id: Password
  parent: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: WindowsElement.Password
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Password
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Password
    path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
    startLine: 54
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the password.\n"
  example: []
  syntax:
    content: public string Password { get; set; }
    content.vb: Public Property Password As String
    parameters: []
    return:
      type: System.String
      description: "\nThe password.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Password*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Domain
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Domain
  id: Domain
  parent: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  langs:
  - csharp
  - vb
  name: Domain
  nameWithType: WindowsElement.Domain
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Domain
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Domain
    path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
    startLine: 68
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the domain.\n"
  example: []
  syntax:
    content: public string Domain { get; set; }
    content.vb: Public Property Domain As String
    parameters: []
    return:
      type: System.String
      description: "\nThe domain.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Domain*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.StsUris
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.StsUris
  id: StsUris
  parent: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  langs:
  - csharp
  - vb
  name: StsUris
  nameWithType: WindowsElement.StsUris
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.StsUris
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: StsUris
    path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
    startLine: 82
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the collection of security token service (STS) URI.\n"
  example: []
  syntax:
    content: public virtual StsUriElementCollection StsUris { get; }
    content.vb: Public Overridable ReadOnly Property StsUris As StsUriElementCollection
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
      description: "\nThe collection of security token service (STS) URI.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.StsUris*
  modifiers.csharp:
  - public
  - virtual
  - get
  modifiers.vb:
  - Public
  - Overridable
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Properties
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Properties
  id: Properties
  parent: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: WindowsElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Properties
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Properties
    path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
    startLine: 107
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the collection of configuration properties.\n"
  example: []
  syntax:
    content: protected override ConfigurationPropertyCollection Properties { get; }
    content.vb: Protected Overrides ReadOnly Property Properties As ConfigurationPropertyCollection
    parameters: []
    return:
      type: ConfigurationPropertyCollection
      description: "\nThe collection of configuration properties.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Properties*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.WindowsElement)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.WindowsElement)
  id: CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.WindowsElement)
  parent: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  langs:
  - csharp
  - vb
  name: CopyFrom(WindowsElement)
  nameWithType: WindowsElement.CopyFrom(WindowsElement)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.WindowsElement)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CopyFrom
    path: src/product/clients/Microsoft.Notifications/Configuration/WindowsElement.cs
    startLine: 130
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nCopies the specified windows element into the current instance.\n"
  example: []
  syntax:
    content: public void CopyFrom(WindowsElement source)
    content.vb: Public Sub CopyFrom(source As WindowsElement)
    parameters:
    - id: source
      type: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
      description: The windows element to copy.
  overload: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.CopyFrom*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UseDefaultCredentials*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UseDefaultCredentials
  isExternal: false
  name: UseDefaultCredentials
  nameWithType: WindowsElement.UseDefaultCredentials
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UseDefaultCredentials
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UserName*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UserName
  isExternal: false
  name: UserName
  nameWithType: WindowsElement.UserName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.UserName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Password*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Password
  isExternal: false
  name: Password
  nameWithType: WindowsElement.Password
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Password
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Domain*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Domain
  isExternal: false
  name: Domain
  nameWithType: WindowsElement.Domain
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Domain
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.StsUris*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.StsUris
  isExternal: false
  name: StsUris
  nameWithType: WindowsElement.StsUris
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.StsUris
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: StsUriElementCollection
  nameWithType: StsUriElementCollection
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElementCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Properties*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Properties
  isExternal: false
  name: Properties
  nameWithType: WindowsElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.Properties
- uid: ConfigurationPropertyCollection
  isExternal: true
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: ConfigurationPropertyCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.CopyFrom*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.CopyFrom
  isExternal: false
  name: CopyFrom
  nameWithType: WindowsElement.CopyFrom
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement.CopyFrom
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: WindowsElement
  nameWithType: WindowsElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
