### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  id: XmlDictionaryReaderQuotasElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  - Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  - Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  - Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  - Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  - Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.Properties
  langs:
  - csharp
  - vb
  name: XmlDictionaryReaderQuotasElement
  nameWithType: XmlDictionaryReaderQuotasElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: XmlDictionaryReaderQuotasElement
    path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 18
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nA configuration element that defines the constraints on the complexity of SOAP messages that can be processed by endpoints configured with a binding. This class cannot be inherited.\n"
  example: []
  syntax:
    content: 'public sealed class XmlDictionaryReaderQuotasElement : ConfigurationElement'
    content.vb: >-
      Public NotInheritable Class XmlDictionaryReaderQuotasElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  id: MaxDepth
  parent: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxDepth
  nameWithType: XmlDictionaryReaderQuotasElement.MaxDepth
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: MaxDepth
    path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 30
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the maximum nested node depth for each read.\n"
  example: []
  syntax:
    content: public int MaxDepth { get; set; }
    content.vb: Public Property MaxDepth As Integer
    parameters: []
    return:
      type: System.Int32
      description: "\nThe maximum nested node depth for each read.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  id: MaxStringContentLength
  parent: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxStringContentLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxStringContentLength
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: MaxStringContentLength
    path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 45
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the maximum number of characters allowed in XML element content.\n"
  example: []
  syntax:
    content: public int MaxStringContentLength { get; set; }
    content.vb: Public Property MaxStringContentLength As Integer
    parameters: []
    return:
      type: System.Int32
      description: "\nThe maximum number of characters allowed in XML element content.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  id: MaxArrayLength
  parent: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxArrayLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxArrayLength
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: MaxArrayLength
    path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 60
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the maximum allowed array length.\n"
  example: []
  syntax:
    content: public int MaxArrayLength { get; set; }
    content.vb: Public Property MaxArrayLength As Integer
    parameters: []
    return:
      type: System.Int32
      description: "\nThe maximum allowed array length.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  id: MaxBytesPerRead
  parent: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxBytesPerRead
  nameWithType: XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: MaxBytesPerRead
    path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 75
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the maximum allowed number of bytes returned for each read.\n"
  example: []
  syntax:
    content: public int MaxBytesPerRead { get; set; }
    content.vb: Public Property MaxBytesPerRead As Integer
    parameters: []
    return:
      type: System.Int32
      description: "\nThe maximum allowed number of bytes returned for each read.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  id: MaxNameTableCharCount
  parent: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: MaxNameTableCharCount
  nameWithType: XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: MaxNameTableCharCount
    path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 90
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the maximum number of characters allowed in a table name.\n"
  example: []
  syntax:
    content: public int MaxNameTableCharCount { get; set; }
    content.vb: Public Property MaxNameTableCharCount As Integer
    parameters: []
    return:
      type: System.Int32
      description: "\nThe maximum number of characters allowed in a table name.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.Properties
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.Properties
  id: Properties
  parent: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: XmlDictionaryReaderQuotasElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.Properties
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Properties
    path: src/product/clients/Microsoft.Notifications/Configuration/XmlDictionaryReaderQuotasElement.cs
    startLine: 142
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the collection of properties.\n"
  example: []
  syntax:
    content: protected override ConfigurationPropertyCollection Properties { get; }
    content.vb: Protected Overrides ReadOnly Property Properties As ConfigurationPropertyCollection
    parameters: []
    return:
      type: ConfigurationPropertyCollection
  overload: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.Properties*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
  isExternal: false
  name: MaxDepth
  nameWithType: XmlDictionaryReaderQuotasElement.MaxDepth
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxDepth
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
  isExternal: false
  name: MaxStringContentLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxStringContentLength
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxStringContentLength
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
  isExternal: false
  name: MaxArrayLength
  nameWithType: XmlDictionaryReaderQuotasElement.MaxArrayLength
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxArrayLength
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  isExternal: false
  name: MaxBytesPerRead
  nameWithType: XmlDictionaryReaderQuotasElement.MaxBytesPerRead
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxBytesPerRead
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  isExternal: false
  name: MaxNameTableCharCount
  nameWithType: XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.MaxNameTableCharCount
- uid: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.Properties*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.Properties
  isExternal: false
  name: Properties
  nameWithType: XmlDictionaryReaderQuotasElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.XmlDictionaryReaderQuotasElement.Properties
- uid: ConfigurationPropertyCollection
  isExternal: true
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: ConfigurationPropertyCollection
