### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.StsUriElement
  id: StsUriElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.StsUriElement.Value
  langs:
  - csharp
  - vb
  name: StsUriElement
  nameWithType: StsUriElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElement
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: StsUriElement
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElement.cs
    startLine: 12
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nRepresents the security token service of the URI element.\n"
  example: []
  syntax:
    content: 'public sealed class StsUriElement : ConfigurationElement'
    content.vb: >-
      Public NotInheritable Class StsUriElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElement.Value
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.StsUriElement.Value
  id: Value
  parent: Microsoft.Azure.NotificationHubs.Configuration.StsUriElement
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: StsUriElement.Value
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElement.Value
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Value
    path: src/product/clients/Microsoft.Notifications/Configuration/StsUriElement.cs
    startLine: 21
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the value of the element.\n"
  example: []
  syntax:
    content: public Uri Value { get; set; }
    content.vb: Public Property Value As Uri
    parameters: []
    return:
      type: Uri
      description: "\nThe value of the element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.StsUriElement.Value*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.StsUriElement.Value*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.StsUriElement.Value
  isExternal: false
  name: Value
  nameWithType: StsUriElement.Value
  fullName: Microsoft.Azure.NotificationHubs.Configuration.StsUriElement.Value
- uid: Uri
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: Uri
