### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  id: SharedSecretElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement)
  - Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerName
  - Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerSecret
  - Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.Properties
  - Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.TokenScope
  langs:
  - csharp
  - vb
  name: SharedSecretElement
  nameWithType: SharedSecretElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: SharedSecretElement
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
    startLine: 11
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nA configuration element that specifies the credentials for a service or client endpoint that is configured to use the <xref href=\"Microsoft.Azure.NotificationHubs.TransportClientCredentialType.SharedSecret\" data-throw-if-not-resolved=\"false\"></xref> credential type.\n"
  example: []
  syntax:
    content: 'public class SharedSecretElement : ConfigurationElement'
    content.vb: >-
      Public Class SharedSecretElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerName
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerName
  id: IssuerName
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  langs:
  - csharp
  - vb
  name: IssuerName
  nameWithType: SharedSecretElement.IssuerName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerName
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: IssuerName
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
    startLine: 32
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the issuer name.\n"
  example: []
  syntax:
    content: public string IssuerName { get; set; }
    content.vb: Public Property IssuerName As String
    parameters: []
    return:
      type: System.String
      description: "\nThe issuer name.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerSecret
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerSecret
  id: IssuerSecret
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  langs:
  - csharp
  - vb
  name: IssuerSecret
  nameWithType: SharedSecretElement.IssuerSecret
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerSecret
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: IssuerSecret
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
    startLine: 47
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the issuer secret key.\n"
  example: []
  syntax:
    content: public string IssuerSecret { get; set; }
    content.vb: Public Property IssuerSecret As String
    parameters: []
    return:
      type: System.String
      description: "\nThe issuer secret key.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerSecret*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.TokenScope
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.TokenScope
  id: TokenScope
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  langs:
  - csharp
  - vb
  name: TokenScope
  nameWithType: SharedSecretElement.TokenScope
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.TokenScope
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: TokenScope
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
    startLine: 62
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the token scope.\n"
  example: []
  syntax:
    content: public TokenScope TokenScope { get; set; }
    content.vb: Public Property TokenScope As TokenScope
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.TokenScope
      description: "\nThe token scope.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.TokenScope*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.Properties
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.Properties
  id: Properties
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: SharedSecretElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.Properties
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Properties
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
    startLine: 82
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the properties of this configuration element that contain the issuer name and the issuer secret key.\n"
  example: []
  syntax:
    content: protected override ConfigurationPropertyCollection Properties { get; }
    content.vb: Protected Overrides ReadOnly Property Properties As ConfigurationPropertyCollection
    parameters: []
    return:
      type: ConfigurationPropertyCollection
      description: "\nThe properties of this configuration element that contain the issuer name and the issuer secret key.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.Properties*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement)
  id: CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement)
  parent: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  langs:
  - csharp
  - vb
  name: CopyFrom(SharedSecretElement)
  nameWithType: SharedSecretElement.CopyFrom(SharedSecretElement)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.CopyFrom(Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CopyFrom
    path: src/product/clients/Microsoft.Notifications/Configuration/SharedSecretElement.cs
    startLine: 103
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nCopies the contents of the specified shared secret configuration element to this configuration element.\n"
  example: []
  syntax:
    content: public void CopyFrom(SharedSecretElement source)
    content.vb: Public Sub CopyFrom(source As SharedSecretElement)
    parameters:
    - id: source
      type: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
      description: The shared secret configuration element to be copied.
  overload: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.CopyFrom*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.NotificationHubs.TransportClientCredentialType.SharedSecret
  commentId: F:Microsoft.Azure.NotificationHubs.TransportClientCredentialType.SharedSecret
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerName*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerName
  isExternal: false
  name: IssuerName
  nameWithType: SharedSecretElement.IssuerName
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerSecret*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerSecret
  isExternal: false
  name: IssuerSecret
  nameWithType: SharedSecretElement.IssuerSecret
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.IssuerSecret
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.TokenScope*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.TokenScope
  isExternal: false
  name: TokenScope
  nameWithType: SharedSecretElement.TokenScope
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.TokenScope
- uid: Microsoft.Azure.NotificationHubs.TokenScope
  commentId: T:Microsoft.Azure.NotificationHubs.TokenScope
  parent: Microsoft.Azure.NotificationHubs
  isExternal: false
  name: TokenScope
  nameWithType: TokenScope
  fullName: Microsoft.Azure.NotificationHubs.TokenScope
- uid: Microsoft.Azure.NotificationHubs
  commentId: N:Microsoft.Azure.NotificationHubs
  isExternal: false
  name: Microsoft.Azure.NotificationHubs
  nameWithType: Microsoft.Azure.NotificationHubs
  fullName: Microsoft.Azure.NotificationHubs
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.Properties*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.Properties
  isExternal: false
  name: Properties
  nameWithType: SharedSecretElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.Properties
- uid: ConfigurationPropertyCollection
  isExternal: true
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: ConfigurationPropertyCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.CopyFrom*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.CopyFrom
  isExternal: false
  name: CopyFrom
  nameWithType: SharedSecretElement.CopyFrom
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement.CopyFrom
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: SharedSecretElement
  nameWithType: SharedSecretElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
