### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  id: TokenProviderElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.CopyFrom(ServiceModelExtensionElement)
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Name
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Properties
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedAccessSignature
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedSecret
  - Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.WindowsAuthentication
  langs:
  - csharp
  - vb
  name: TokenProviderElement
  nameWithType: TokenProviderElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: TokenProviderElement
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
    startLine: 13
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nRepresents the configuration element that specifies the token provider for the Service Bus.\n"
  example: []
  syntax:
    content: 'public class TokenProviderElement : ClientCredentialsElement'
    content.vb: >-
      Public Class TokenProviderElement
          Inherits ClientCredentialsElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Name
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Name
  id: Name
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: TokenProviderElement.Name
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Name
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Name
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
    startLine: 34
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the provider name.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
      description: "\nThe provider name.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedSecret
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedSecret
  id: SharedSecret
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  langs:
  - csharp
  - vb
  name: SharedSecret
  nameWithType: TokenProviderElement.SharedSecret
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedSecret
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: SharedSecret
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
    startLine: 49
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the shared secret element contained in the token provider element.\n"
  example: []
  syntax:
    content: public SharedSecretElement SharedSecret { get; }
    content.vb: Public ReadOnly Property SharedSecret As SharedSecretElement
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
      description: "\nThe shared secret element contained in the token provider element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedSecret*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.WindowsAuthentication
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.WindowsAuthentication
  id: WindowsAuthentication
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  langs:
  - csharp
  - vb
  name: WindowsAuthentication
  nameWithType: TokenProviderElement.WindowsAuthentication
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.WindowsAuthentication
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: WindowsAuthentication
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
    startLine: 62
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the Windows authentication settings for this element.\n"
  example: []
  syntax:
    content: public WindowsElement WindowsAuthentication { get; }
    content.vb: Public ReadOnly Property WindowsAuthentication As WindowsElement
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
      description: "\nThe Windows authentication settings for this element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.WindowsAuthentication*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedAccessSignature
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedAccessSignature
  id: SharedAccessSignature
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  langs:
  - csharp
  - vb
  name: SharedAccessSignature
  nameWithType: TokenProviderElement.SharedAccessSignature
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedAccessSignature
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: SharedAccessSignature
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
    startLine: 75
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the shared access signature element.\n"
  example: []
  syntax:
    content: public SharedAccessSignatureElement SharedAccessSignature { get; }
    content.vb: Public ReadOnly Property SharedAccessSignature As SharedAccessSignatureElement
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
      description: "\nThe shared access signature element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedAccessSignature*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Properties
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Properties
  id: Properties
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: TokenProviderElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Properties
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Properties
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
    startLine: 93
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the collection of properties contained in the configuration element.\n"
  example: []
  syntax:
    content: protected override ConfigurationPropertyCollection Properties { get; }
    content.vb: Protected Overrides ReadOnly Property Properties As ConfigurationPropertyCollection
    parameters: []
    return:
      type: ConfigurationPropertyCollection
      description: "\nThe collection of properties contained in the configuration element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Properties*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.CopyFrom(ServiceModelExtensionElement)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.CopyFrom(ServiceModelExtensionElement)
  id: CopyFrom(ServiceModelExtensionElement)
  parent: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement
  langs:
  - csharp
  - vb
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: TokenProviderElement.CopyFrom(ServiceModelExtensionElement)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CopyFrom
    path: src/product/clients/Microsoft.Notifications/Configuration/TokenProviderElement.cs
    startLine: 140
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nCopies the contents of the specified configuration element to this configuration element.\n"
  example: []
  syntax:
    content: public override void CopyFrom(ServiceModelExtensionElement from)
    content.vb: Public Overrides Sub CopyFrom(from As ServiceModelExtensionElement)
    parameters:
    - id: from
      type: ServiceModelExtensionElement
      description: The configuration element to copy the contents from.
  overload: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.CopyFrom*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Name*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Name
  isExternal: false
  name: Name
  nameWithType: TokenProviderElement.Name
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedSecret*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedSecret
  isExternal: false
  name: SharedSecret
  nameWithType: TokenProviderElement.SharedSecret
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedSecret
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: SharedSecretElement
  nameWithType: SharedSecretElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedSecretElement
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.WindowsAuthentication*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.WindowsAuthentication
  isExternal: false
  name: WindowsAuthentication
  nameWithType: TokenProviderElement.WindowsAuthentication
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.WindowsAuthentication
- uid: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: WindowsElement
  nameWithType: WindowsElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.WindowsElement
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedAccessSignature*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedAccessSignature
  isExternal: false
  name: SharedAccessSignature
  nameWithType: TokenProviderElement.SharedAccessSignature
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.SharedAccessSignature
- uid: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: SharedAccessSignatureElement
  nameWithType: SharedAccessSignatureElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.SharedAccessSignatureElement
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Properties*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Properties
  isExternal: false
  name: Properties
  nameWithType: TokenProviderElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.Properties
- uid: ConfigurationPropertyCollection
  isExternal: true
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: ConfigurationPropertyCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.CopyFrom*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.CopyFrom
  isExternal: false
  name: CopyFrom
  nameWithType: TokenProviderElement.CopyFrom
  fullName: Microsoft.Azure.NotificationHubs.Configuration.TokenProviderElement.CopyFrom
- uid: ServiceModelExtensionElement
  isExternal: true
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: ServiceModelExtensionElement
