### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.ConnectivitySettings
  commentId: T:Microsoft.Azure.NotificationHubs.ConnectivitySettings
  id: ConnectivitySettings
  parent: Microsoft.Azure.NotificationHubs
  children:
  - Microsoft.Azure.NotificationHubs.ConnectivitySettings.#ctor
  - Microsoft.Azure.NotificationHubs.ConnectivitySettings.connectivityMode
  - Microsoft.Azure.NotificationHubs.ConnectivitySettings.IsReadOnly
  - Microsoft.Azure.NotificationHubs.ConnectivitySettings.Mode
  langs:
  - csharp
  - vb
  name: ConnectivitySettings
  nameWithType: ConnectivitySettings
  fullName: Microsoft.Azure.NotificationHubs.ConnectivitySettings
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: ConnectivitySettings
    path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
    startLine: 29
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nHolds the connectivity settings effective for all Windows Azure Service Bus-based endpoints that are active in the current application domain.\n"
  example: []
  syntax:
    content: public class ConnectivitySettings
    content.vb: Public Class ConnectivitySettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.NotificationHubs.ConnectivitySettings.connectivityMode
  commentId: F:Microsoft.Azure.NotificationHubs.ConnectivitySettings.connectivityMode
  id: connectivityMode
  parent: Microsoft.Azure.NotificationHubs.ConnectivitySettings
  langs:
  - csharp
  - vb
  name: connectivityMode
  nameWithType: ConnectivitySettings.connectivityMode
  fullName: Microsoft.Azure.NotificationHubs.ConnectivitySettings.connectivityMode
  type: Field
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: connectivityMode
    path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
    startLine: 34
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nContains the <xref href=\"Microsoft.Azure.NotificationHubs.ConnectivityMode\" data-throw-if-not-resolved=\"false\"></xref> for the current instance.\n"
  example: []
  syntax:
    content: protected ConnectivityMode connectivityMode
    content.vb: Protected connectivityMode As ConnectivityMode
    return:
      type: Microsoft.Azure.NotificationHubs.ConnectivityMode
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Microsoft.Azure.NotificationHubs.ConnectivitySettings.#ctor
  commentId: M:Microsoft.Azure.NotificationHubs.ConnectivitySettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.NotificationHubs.ConnectivitySettings
  langs:
  - csharp
  - vb
  name: ConnectivitySettings()
  nameWithType: ConnectivitySettings.ConnectivitySettings()
  fullName: Microsoft.Azure.NotificationHubs.ConnectivitySettings.ConnectivitySettings()
  type: Constructor
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: .ctor
    path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
    startLine: 39
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nCreate new instance of ConnectivitySettings class\n"
  example: []
  syntax:
    content: public ConnectivitySettings()
    content.vb: Public Sub New
  overload: Microsoft.Azure.NotificationHubs.ConnectivitySettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.ConnectivitySettings.Mode
  commentId: P:Microsoft.Azure.NotificationHubs.ConnectivitySettings.Mode
  id: Mode
  parent: Microsoft.Azure.NotificationHubs.ConnectivitySettings
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: ConnectivitySettings.Mode
  fullName: Microsoft.Azure.NotificationHubs.ConnectivitySettings.Mode
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Mode
    path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
    startLine: 50
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nGets or sets the connectivity mode for the current application domain.\n"
  example: []
  syntax:
    content: public ConnectivityMode Mode { get; set; }
    content.vb: Public Property Mode As ConnectivityMode
    parameters: []
    return:
      type: Microsoft.Azure.NotificationHubs.ConnectivityMode
      description: "\nReturns <xref href=\"Microsoft.Azure.NotificationHubs.ConnectivityMode\" data-throw-if-not-resolved=\"false\"></xref>.Contains the connectivity mode.\n"
  overload: Microsoft.Azure.NotificationHubs.ConnectivitySettings.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.ConnectivitySettings.IsReadOnly
  commentId: P:Microsoft.Azure.NotificationHubs.ConnectivitySettings.IsReadOnly
  id: IsReadOnly
  parent: Microsoft.Azure.NotificationHubs.ConnectivitySettings
  langs:
  - csharp
  - vb
  name: IsReadOnly
  nameWithType: ConnectivitySettings.IsReadOnly
  fullName: Microsoft.Azure.NotificationHubs.ConnectivitySettings.IsReadOnly
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: IsReadOnly
    path: src/product/clients/Microsoft.Notifications/Description/ConnectivitySettings.cs
    startLine: 75
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs
  summary: "\nGets a value that determines if the connectivity settings are read-only.\n"
  example: []
  syntax:
    content: protected virtual bool IsReadOnly { get; }
    content.vb: Protected Overridable ReadOnly Property IsReadOnly As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: "\ntrue if the connectivity settings are read-only; otherwise, false.\n"
  overload: Microsoft.Azure.NotificationHubs.ConnectivitySettings.IsReadOnly*
  modifiers.csharp:
  - protected
  - virtual
  - get
  modifiers.vb:
  - Protected
  - Overridable
  - ReadOnly
references:
- uid: Microsoft.Azure.NotificationHubs
  commentId: N:Microsoft.Azure.NotificationHubs
  isExternal: false
  name: Microsoft.Azure.NotificationHubs
  nameWithType: Microsoft.Azure.NotificationHubs
  fullName: Microsoft.Azure.NotificationHubs
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.ConnectivityMode
  commentId: T:Microsoft.Azure.NotificationHubs.ConnectivityMode
  parent: Microsoft.Azure.NotificationHubs
  isExternal: false
  name: ConnectivityMode
  nameWithType: ConnectivityMode
  fullName: Microsoft.Azure.NotificationHubs.ConnectivityMode
- uid: Microsoft.Azure.NotificationHubs.ConnectivitySettings.#ctor*
  commentId: Overload:Microsoft.Azure.NotificationHubs.ConnectivitySettings.#ctor
  isExternal: false
  name: ConnectivitySettings
  nameWithType: ConnectivitySettings.ConnectivitySettings
  fullName: Microsoft.Azure.NotificationHubs.ConnectivitySettings.ConnectivitySettings
- uid: Microsoft.Azure.NotificationHubs.ConnectivitySettings.Mode*
  commentId: Overload:Microsoft.Azure.NotificationHubs.ConnectivitySettings.Mode
  isExternal: false
  name: Mode
  nameWithType: ConnectivitySettings.Mode
  fullName: Microsoft.Azure.NotificationHubs.ConnectivitySettings.Mode
- uid: Microsoft.Azure.NotificationHubs.ConnectivitySettings.IsReadOnly*
  commentId: Overload:Microsoft.Azure.NotificationHubs.ConnectivitySettings.IsReadOnly
  isExternal: false
  name: IsReadOnly
  nameWithType: ConnectivitySettings.IsReadOnly
  fullName: Microsoft.Azure.NotificationHubs.ConnectivitySettings.IsReadOnly
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
