### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.IssuerElement
  id: IssuerElement
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Address
  - Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.CopyFrom(ConfigurationElement)
  - Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Properties
  langs:
  - csharp
  - vb
  name: IssuerElement
  nameWithType: IssuerElement
  fullName: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement
  type: Class
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/IssuerElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: IssuerElement
    path: src/product/clients/Microsoft.Notifications/Configuration/IssuerElement.cs
    startLine: 12
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nA configuration element that describes an issuer of a token for the Windows Azure Notification Hubs.\n"
  example: []
  syntax:
    content: 'public class IssuerElement : ConfigurationElement'
    content.vb: >-
      Public Class IssuerElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Address
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Address
  id: Address
  parent: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement
  langs:
  - csharp
  - vb
  name: Address
  nameWithType: IssuerElement.Address
  fullName: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Address
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/IssuerElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Address
    path: src/product/clients/Microsoft.Notifications/Configuration/IssuerElement.cs
    startLine: 27
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets or sets the URI address of the token issuer.\n"
  example: []
  syntax:
    content: public string Address { get; set; }
    content.vb: Public Property Address As String
    parameters: []
    return:
      type: System.String
      description: "\nThe URI address of the token issuer.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Address*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Properties
  commentId: P:Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Properties
  id: Properties
  parent: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: IssuerElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Properties
  type: Property
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/IssuerElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: Properties
    path: src/product/clients/Microsoft.Notifications/Configuration/IssuerElement.cs
    startLine: 42
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nGets the collection of properties contained in this configuration element.\n"
  example: []
  syntax:
    content: protected override ConfigurationPropertyCollection Properties { get; }
    content.vb: Protected Overrides ReadOnly Property Properties As ConfigurationPropertyCollection
    parameters: []
    return:
      type: ConfigurationPropertyCollection
      description: "\nThe collection of properties contained in this configuration element.\n"
  overload: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Properties*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
- uid: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.CopyFrom(ConfigurationElement)
  commentId: M:Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.CopyFrom(ConfigurationElement)
  id: CopyFrom(ConfigurationElement)
  parent: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement
  langs:
  - csharp
  - vb
  name: CopyFrom(ConfigurationElement)
  nameWithType: IssuerElement.CopyFrom(ConfigurationElement)
  fullName: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.CopyFrom(ConfigurationElement)
  type: Method
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/IssuerElement.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
    id: CopyFrom
    path: src/product/clients/Microsoft.Notifications/Configuration/IssuerElement.cs
    startLine: 61
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nCopies the contents of the specified configuration element to this configuration element.\n"
  example: []
  syntax:
    content: public void CopyFrom(ConfigurationElement from)
    content.vb: Public Sub CopyFrom(from As ConfigurationElement)
    parameters:
    - id: from
      type: ConfigurationElement
      description: The configuration element to copy the contents from.
  overload: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.CopyFrom*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Address*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Address
  isExternal: false
  name: Address
  nameWithType: IssuerElement.Address
  fullName: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Address
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Properties*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Properties
  isExternal: false
  name: Properties
  nameWithType: IssuerElement.Properties
  fullName: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.Properties
- uid: ConfigurationPropertyCollection
  isExternal: true
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: ConfigurationPropertyCollection
- uid: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.CopyFrom*
  commentId: Overload:Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.CopyFrom
  isExternal: false
  name: CopyFrom
  nameWithType: IssuerElement.CopyFrom
  fullName: Microsoft.Azure.NotificationHubs.Configuration.IssuerElement.CopyFrom
- uid: ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: ConfigurationElement
