### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  id: ServiceBusSectionType
  parent: Microsoft.Azure.NotificationHubs.Configuration
  children:
  - Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.All
  - Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.MessagingFactory
  - Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.NamespaceManager
  langs:
  - csharp
  - vb
  name: ServiceBusSectionType
  nameWithType: ServiceBusSectionType
  fullName: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  type: Enum
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/ServiceBusSectionType.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
      commit: 48349917176c322d86f63d8fcfb752f5810d37ac
    id: ServiceBusSectionType
    path: src/msazure-vso-notificationhubs/src/product/clients/Microsoft.Notifications/Configuration/ServiceBusSectionType.cs
    startLine: 11
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nEnumerates the azure notification hubs section type.\n"
  example: []
  syntax:
    content: >-
      [Serializable]

      public enum ServiceBusSectionType
    content.vb: >-
      <Serializable>

      Public Enum ServiceBusSectionType
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.All
  commentId: F:Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.All
  id: All
  parent: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  langs:
  - csharp
  - vb
  name: All
  nameWithType: ServiceBusSectionType.All
  fullName: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.All
  type: Field
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/ServiceBusSectionType.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
      commit: 48349917176c322d86f63d8fcfb752f5810d37ac
    id: All
    path: src/msazure-vso-notificationhubs/src/product/clients/Microsoft.Notifications/Configuration/ServiceBusSectionType.cs
    startLine: 17
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nAll\n"
  example: []
  syntax:
    content: All = 0
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.NamespaceManager
  commentId: F:Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.NamespaceManager
  id: NamespaceManager
  parent: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  langs:
  - csharp
  - vb
  name: NamespaceManager
  nameWithType: ServiceBusSectionType.NamespaceManager
  fullName: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.NamespaceManager
  type: Field
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/ServiceBusSectionType.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
      commit: 48349917176c322d86f63d8fcfb752f5810d37ac
    id: NamespaceManager
    path: src/msazure-vso-notificationhubs/src/product/clients/Microsoft.Notifications/Configuration/ServiceBusSectionType.cs
    startLine: 22
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nThe namespace manager\n"
  example: []
  syntax:
    content: NamespaceManager = 1
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.MessagingFactory
  commentId: F:Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.MessagingFactory
  id: MessagingFactory
  parent: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  langs:
  - csharp
  - vb
  name: MessagingFactory
  nameWithType: ServiceBusSectionType.MessagingFactory
  fullName: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType.MessagingFactory
  type: Field
  source:
    remote:
      path: src/product/clients/Microsoft.Notifications/Configuration/ServiceBusSectionType.cs
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/AAPT-Mobile-Push
      commit: 48349917176c322d86f63d8fcfb752f5810d37ac
    id: MessagingFactory
    path: src/msazure-vso-notificationhubs/src/product/clients/Microsoft.Notifications/Configuration/ServiceBusSectionType.cs
    startLine: 27
  assemblies:
  - Microsoft.Notifications
  namespace: Microsoft.Azure.NotificationHubs.Configuration
  summary: "\nThe messaging factory\n"
  example: []
  syntax:
    content: MessagingFactory = 2
    return:
      type: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.NotificationHubs.Configuration
  commentId: N:Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: Microsoft.Azure.NotificationHubs.Configuration
  nameWithType: Microsoft.Azure.NotificationHubs.Configuration
  fullName: Microsoft.Azure.NotificationHubs.Configuration
- uid: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  commentId: T:Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
  parent: Microsoft.Azure.NotificationHubs.Configuration
  isExternal: false
  name: ServiceBusSectionType
  nameWithType: ServiceBusSectionType
  fullName: Microsoft.Azure.NotificationHubs.Configuration.ServiceBusSectionType
