items:
- uid: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  commentId: T:Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  id: EncryptionConfigType
  parent: Microsoft.Azure.Management.DataLake.Store.Models
  children:
  - Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.ServiceManaged
  - Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.UserManaged
  langs:
  - csharp
  - vb
  name: EncryptionConfigType
  fullName: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: EncryptionConfigType
    path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.DataLake.Store
  packages:
  - Microsoft.Azure.Management.DataLake.Store(0.12.6-preview)
  namespace: Microsoft.Azure.Management.DataLake.Store.Models
  summary: "\nDefines values for EncryptionConfigType.\n"
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof (StringEnumConverter))]

      public enum EncryptionConfigType
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum EncryptionConfigType
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.UserManaged
  commentId: F:Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.UserManaged
  id: UserManaged
  parent: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  langs:
  - csharp
  - vb
  name: UserManaged
  fullName: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.UserManaged
  type: Field
  source:
    remote:
      path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: UserManaged
    path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.DataLake.Store
  packages:
  - Microsoft.Azure.Management.DataLake.Store(0.12.6-preview)
  namespace: Microsoft.Azure.Management.DataLake.Store.Models
  syntax:
    content: >-
      [EnumMember(Value = "UserManaged")]

      UserManaged = 0
    content.vb: >-
      <EnumMember(Value:="UserManaged")>

      UserManaged = 0
    return:
      type: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: UserManaged
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.ServiceManaged
  commentId: F:Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.ServiceManaged
  id: ServiceManaged
  parent: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  langs:
  - csharp
  - vb
  name: ServiceManaged
  fullName: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.ServiceManaged
  type: Field
  source:
    remote:
      path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ServiceManaged
    path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.DataLake.Store
  packages:
  - Microsoft.Azure.Management.DataLake.Store(0.12.6-preview)
  namespace: Microsoft.Azure.Management.DataLake.Store.Models
  syntax:
    content: >-
      [EnumMember(Value = "ServiceManaged")]

      ServiceManaged = 1
    content.vb: >-
      <EnumMember(Value:="ServiceManaged")>

      ServiceManaged = 1
    return:
      type: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: ServiceManaged
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.DataLake.Store.Models
  isExternal: false
  name: Microsoft.Azure.Management.DataLake.Store.Models
  fullName: Microsoft.Azure.Management.DataLake.Store.Models
- uid: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  parent: Microsoft.Azure.Management.DataLake.Store.Models
  isExternal: false
  name: EncryptionConfigType
  fullName: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
