### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  id: ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor(System.String)
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration
  nameWithType: ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfiguration
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nRepresents an Azure SQL Server disaster recovery configuration.\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfiguration : ResourceBaseExtended'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfiguration
          Inherits ResourceBaseExtended
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  id: Properties
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: ServerDisasterRecoveryConfiguration.Properties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Properties
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets or sets the properties representing the resource.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationProperties Properties { get; set; }
    content.vb: Public Property Properties As ServerDisasterRecoveryConfigurationProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration()
  nameWithType: ServerDisasterRecoveryConfiguration.ServerDisasterRecoveryConfiguration()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.ServerDisasterRecoveryConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfiguration class.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfiguration()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor(System.String)
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration(String)
  nameWithType: ServerDisasterRecoveryConfiguration.ServerDisasterRecoveryConfiguration(String)
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.ServerDisasterRecoveryConfiguration(System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfiguration.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfiguration class with required arguments.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfiguration(string location)
    content.vb: Public Sub New(location As String)
    parameters:
    - id: location
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  commentId: N:Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  nameWithType: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
  isExternal: false
  name: Properties
  nameWithType: ServerDisasterRecoveryConfiguration.Properties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.Properties
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ServerDisasterRecoveryConfigurationProperties
  nameWithType: ServerDisasterRecoveryConfigurationProperties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.#ctor
  isExternal: false
  name: ServerDisasterRecoveryConfiguration
  nameWithType: ServerDisasterRecoveryConfiguration.ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration.ServerDisasterRecoveryConfiguration
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
