### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  id: ServerDisasterRecoveryConfigurationGetResponse
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationGetResponse
  nameWithType: ServerDisasterRecoveryConfigurationGetResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfigurationGetResponse
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nRepresents the response to a get server disaster recovery configuration\nrequest.\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationGetResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationGetResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  id: ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration
  nameWithType: ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfiguration
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets or sets the Azure Sql Server disaster recovery\nconfiguration.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfiguration ServerDisasterRecoveryConfiguration { get; set; }
    content.vb: Public Property ServerDisasterRecoveryConfiguration As ServerDisasterRecoveryConfiguration
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationGetResponse()
  nameWithType: ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfigurationGetResponse()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfigurationGetResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationGetResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfigurationGetResponse class.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationGetResponse()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  commentId: N:Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  nameWithType: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  isExternal: false
  name: ServerDisasterRecoveryConfiguration
  nameWithType: ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfiguration
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ServerDisasterRecoveryConfiguration
  nameWithType: ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.#ctor
  isExternal: false
  name: ServerDisasterRecoveryConfigurationGetResponse
  nameWithType: ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfigurationGetResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationGetResponse.ServerDisasterRecoveryConfigurationGetResponse
