### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  id: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties,System.String)
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nCreate or update Azure SQL Server disaster recovery configuration\nparameters.\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationCreateOrUpdateParameters : ResourceBase'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
          Inherits ResourceBase
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  id: Properties
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Properties
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nRequired. Gets or sets the properties of the request.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationCreateOrUpdateProperties Properties { get; set; }
    content.vb: Public Property Properties As ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters()
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfigurationCreateOrUpdateParameters class.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationCreateOrUpdateParameters()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties,System.String)
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties,System.String)
  id: '#ctor(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties,System.String)'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters(ServerDisasterRecoveryConfigurationCreateOrUpdateProperties, String)
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters(ServerDisasterRecoveryConfigurationCreateOrUpdateProperties, String)
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters(Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.cs
    startLine: 58
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfigurationCreateOrUpdateParameters class\nwith required arguments.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationCreateOrUpdateParameters(ServerDisasterRecoveryConfigurationCreateOrUpdateProperties properties, string location)
    content.vb: Public Sub New(properties As ServerDisasterRecoveryConfigurationCreateOrUpdateProperties, location As String)
    parameters:
    - id: properties
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
    - id: location
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  commentId: N:Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  nameWithType: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  isExternal: false
  name: Properties
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.Properties
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.#ctor
  isExternal: false
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters.ServerDisasterRecoveryConfigurationCreateOrUpdateParameters
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
