### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  id: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nResponse for long running Azure Sql server disaster recovery\nconfiguration operation.\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationCreateOrUpdateResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  id: Error
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: Error
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Error
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional.\n"
  example: []
  syntax:
    content: public ErrorResponse Error { get; set; }
    content.vb: Public Property Error As ErrorResponse
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ErrorResponse
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  id: OperationStatusLink
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: OperationStatusLink
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: OperationStatusLink
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional.\n"
  example: []
  syntax:
    content: public string OperationStatusLink { get; set; }
    content.vb: Public Property OperationStatusLink As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  id: RetryAfter
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: RetryAfter
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: RetryAfter
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional.\n"
  example: []
  syntax:
    content: public int RetryAfter { get; set; }
    content.vb: Public Property RetryAfter As Integer
    parameters: []
    return:
      type: System.Int32
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  id: ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfiguration
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfiguration
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets or sets the object that represents the Azure Sql\nServer disaster recovery configuration.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfiguration ServerDisasterRecoveryConfiguration { get; set; }
    content.vb: Public Property ServerDisasterRecoveryConfiguration As ServerDisasterRecoveryConfiguration
    parameters: []
    return:
      type: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  id: Status
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: Status
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Status
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 84
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional.\n"
  example: []
  syntax:
    content: public OperationStatus Status { get; set; }
    content.vb: Public Property Status As OperationStatus
    parameters: []
    return:
      type: OperationStatus
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse()
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.cs
    startLine: 94
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfigurationCreateOrUpdateResponse class.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationCreateOrUpdateResponse()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  commentId: N:Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  nameWithType: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  isExternal: false
  name: Error
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Error
- uid: Microsoft.Azure.Management.Sql.Models.ErrorResponse
  commentId: T:Microsoft.Azure.Management.Sql.Models.ErrorResponse
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ErrorResponse
  nameWithType: ErrorResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ErrorResponse
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  isExternal: false
  name: OperationStatusLink
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.OperationStatusLink
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  isExternal: false
  name: RetryAfter
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.RetryAfter
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  isExternal: false
  name: ServerDisasterRecoveryConfiguration
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfiguration
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  parent: Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: ServerDisasterRecoveryConfiguration
  nameWithType: ServerDisasterRecoveryConfiguration
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  isExternal: false
  name: Status
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.Status
- uid: OperationStatus
  isExternal: true
  name: OperationStatus
  nameWithType: OperationStatus
  fullName: OperationStatus
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.#ctor
  isExternal: false
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse.ServerDisasterRecoveryConfigurationCreateOrUpdateResponse
