### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  id: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nCreate or update Azure Sql Server disaster recovery configuration\nparameters properties.\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationCreateOrUpdateProperties : object'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover
  id: AutoFailover
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: AutoFailover
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: AutoFailover
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Whether or not automatic failover is enabled.\n"
  example: []
  syntax:
    content: public string AutoFailover { get; set; }
    content.vb: Public Property AutoFailover As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy
  id: FailoverPolicy
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: FailoverPolicy
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: FailoverPolicy
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. The policy for automatically failing over.\n"
  example: []
  syntax:
    content: public string FailoverPolicy { get; set; }
    content.vb: Public Property FailoverPolicy As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName
  id: PartnerLogicalServerName
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: PartnerLogicalServerName
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: PartnerLogicalServerName
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets the name of the partner server.\n"
  example: []
  syntax:
    content: public string PartnerLogicalServerName { get; set; }
    content.vb: Public Property PartnerLogicalServerName As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId
  id: PartnerServerId
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: PartnerServerId
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: PartnerServerId
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets the id of the partner server.\n"
  example: []
  syntax:
    content: public string PartnerServerId { get; set; }
    content.vb: Public Property PartnerServerId As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role
  id: Role
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: Role
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Role
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
    startLine: 81
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets the role of the server.\n"
  example: []
  syntax:
    content: public string Role { get; set; }
    content.vb: Public Property Role As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type
  id: Type
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Type
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
    startLine: 92
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. The type of server disaster recovery configuration.\n"
  example: []
  syntax:
    content: public string Type { get; set; }
    content.vb: Public Property Type As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties()
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.cs
    startLine: 102
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfigurationCreateOrUpdateProperties class.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationCreateOrUpdateProperties()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  commentId: N:Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  nameWithType: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover
  isExternal: false
  name: AutoFailover
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.AutoFailover
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy
  isExternal: false
  name: FailoverPolicy
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.FailoverPolicy
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName
  isExternal: false
  name: PartnerLogicalServerName
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerLogicalServerName
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId
  isExternal: false
  name: PartnerServerId
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.PartnerServerId
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role
  isExternal: false
  name: Role
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Role
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type
  isExternal: false
  name: Type
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.Type
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.#ctor
  isExternal: false
  name: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  nameWithType: ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties.ServerDisasterRecoveryConfigurationCreateOrUpdateProperties
