### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  id: ServerDisasterRecoveryConfigurationProperties
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.AutoFailover
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.FailoverPolicy
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerServerId
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Role
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Type
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationProperties
  nameWithType: ServerDisasterRecoveryConfigurationProperties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfigurationProperties
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nRepresents the properties of an Azure SQL Server disaster recovery\nconfiguration.\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationProperties : object'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationProperties
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.AutoFailover
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.AutoFailover
  id: AutoFailover
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  langs:
  - csharp
  - vb
  name: AutoFailover
  nameWithType: ServerDisasterRecoveryConfigurationProperties.AutoFailover
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.AutoFailover
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: AutoFailover
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Whether or not automatic failover is enabled.\n"
  example: []
  syntax:
    content: public string AutoFailover { get; set; }
    content.vb: Public Property AutoFailover As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.AutoFailover*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.FailoverPolicy
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.FailoverPolicy
  id: FailoverPolicy
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  langs:
  - csharp
  - vb
  name: FailoverPolicy
  nameWithType: ServerDisasterRecoveryConfigurationProperties.FailoverPolicy
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.FailoverPolicy
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: FailoverPolicy
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. The policy for automatically failing over.\n"
  example: []
  syntax:
    content: public string FailoverPolicy { get; set; }
    content.vb: Public Property FailoverPolicy As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.FailoverPolicy*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName
  id: PartnerLogicalServerName
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  langs:
  - csharp
  - vb
  name: PartnerLogicalServerName
  nameWithType: ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: PartnerLogicalServerName
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets the name of the partner server.\n"
  example: []
  syntax:
    content: public string PartnerLogicalServerName { get; set; }
    content.vb: Public Property PartnerLogicalServerName As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerServerId
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerServerId
  id: PartnerServerId
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  langs:
  - csharp
  - vb
  name: PartnerServerId
  nameWithType: ServerDisasterRecoveryConfigurationProperties.PartnerServerId
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerServerId
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: PartnerServerId
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets the id path the partner server.\n"
  example: []
  syntax:
    content: public string PartnerServerId { get; set; }
    content.vb: Public Property PartnerServerId As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerServerId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Role
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Role
  id: Role
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  langs:
  - csharp
  - vb
  name: Role
  nameWithType: ServerDisasterRecoveryConfigurationProperties.Role
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Role
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Role
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
    startLine: 81
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets the role of the server.\n"
  example: []
  syntax:
    content: public string Role { get; set; }
    content.vb: Public Property Role As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Role*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Type
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Type
  id: Type
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: ServerDisasterRecoveryConfigurationProperties.Type
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Type
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Type
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
    startLine: 92
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. The type of server disaster recovery configuration.\n"
  example: []
  syntax:
    content: public string Type { get; set; }
    content.vb: Public Property Type As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Type*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationProperties()
  nameWithType: ServerDisasterRecoveryConfigurationProperties.ServerDisasterRecoveryConfigurationProperties()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.ServerDisasterRecoveryConfigurationProperties()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationProperties.cs
    startLine: 102
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfigurationProperties class.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationProperties()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  commentId: N:Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  nameWithType: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.AutoFailover*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.AutoFailover
  isExternal: false
  name: AutoFailover
  nameWithType: ServerDisasterRecoveryConfigurationProperties.AutoFailover
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.AutoFailover
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.FailoverPolicy*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.FailoverPolicy
  isExternal: false
  name: FailoverPolicy
  nameWithType: ServerDisasterRecoveryConfigurationProperties.FailoverPolicy
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.FailoverPolicy
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName
  isExternal: false
  name: PartnerLogicalServerName
  nameWithType: ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerLogicalServerName
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerServerId*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerServerId
  isExternal: false
  name: PartnerServerId
  nameWithType: ServerDisasterRecoveryConfigurationProperties.PartnerServerId
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.PartnerServerId
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Role*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Role
  isExternal: false
  name: Role
  nameWithType: ServerDisasterRecoveryConfigurationProperties.Role
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Role
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Type*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Type
  isExternal: false
  name: Type
  nameWithType: ServerDisasterRecoveryConfigurationProperties.Type
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.Type
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.#ctor
  isExternal: false
  name: ServerDisasterRecoveryConfigurationProperties
  nameWithType: ServerDisasterRecoveryConfigurationProperties.ServerDisasterRecoveryConfigurationProperties
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationProperties.ServerDisasterRecoveryConfigurationProperties
