### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  commentId: T:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  id: ServerDisasterRecoveryConfigurationListResponse
  parent: Microsoft.Azure.Management.Sql.Models
  children:
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
  - Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationListResponse
  nameWithType: ServerDisasterRecoveryConfigurationListResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfigurationListResponse
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nRepresents the response to a List Azure Sql Server disaster recovery\nconfiguration request.\n"
  example: []
  syntax:
    content: 'public class ServerDisasterRecoveryConfigurationListResponse : AzureOperationResponse, IEnumerable<ServerDisasterRecoveryConfiguration>'
    content.vb: >-
      Public Class ServerDisasterRecoveryConfigurationListResponse
          Inherits AzureOperationResponse
          Implements IEnumerable(Of ServerDisasterRecoveryConfiguration)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  commentId: P:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  id: ServerDisasterRecoveryConfigurations
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurations
  nameWithType: ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ServerDisasterRecoveryConfigurations
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nOptional. Gets or sets the list of Azure Sql Server disaster\nrecovery configurations.\n"
  example: []
  syntax:
    content: public IList<ServerDisasterRecoveryConfiguration> ServerDisasterRecoveryConfigurations { get; set; }
    content.vb: Public Property ServerDisasterRecoveryConfigurations As IList(Of ServerDisasterRecoveryConfiguration)
    parameters: []
    return:
      type: IList{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  langs:
  - csharp
  - vb
  name: ServerDisasterRecoveryConfigurationListResponse()
  nameWithType: ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurationListResponse()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurationListResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nInitializes a new instance of the\nServerDisasterRecoveryConfigurationListResponse class.\n"
  example: []
  syntax:
    content: public ServerDisasterRecoveryConfigurationListResponse()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
  commentId: M:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse
  langs:
  - csharp
  - vb
  name: GetEnumerator()
  nameWithType: ServerDisasterRecoveryConfigurationListResponse.GetEnumerator()
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: GetEnumerator
    path: src/ResourceManagement/Sql/SqlManagement/Generated/Models/ServerDisasterRecoveryConfigurationListResponse.cs
    startLine: 60
  assemblies:
  - Microsoft.Azure.Management.Sql
  namespace: Microsoft.Azure.Management.Sql.Models
  summary: "\nGets the sequence of ServerDisasterRecoveryConfigurations.\n"
  example: []
  syntax:
    content: public IEnumerator<ServerDisasterRecoveryConfiguration> GetEnumerator()
    content.vb: Public Function GetEnumerator As IEnumerator(Of ServerDisasterRecoveryConfiguration)
    return:
      type: IEnumerator{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  overload: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Sql.Models
  commentId: N:Microsoft.Azure.Management.Sql.Models
  isExternal: false
  name: Microsoft.Azure.Management.Sql.Models
  nameWithType: Microsoft.Azure.Management.Sql.Models
  fullName: Microsoft.Azure.Management.Sql.Models
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  isExternal: false
  name: ServerDisasterRecoveryConfigurations
  nameWithType: ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurations
- uid: IList{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  commentId: '!:IList{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}'
  definition: IList`1
  name: IList<ServerDisasterRecoveryConfiguration>
  nameWithType: IList<ServerDisasterRecoveryConfiguration>
  fullName: IList<Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration>
  nameWithType.vb: IList(Of ServerDisasterRecoveryConfiguration)
  fullname.vb: IList(Of Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration)
  name.vb: IList(Of ServerDisasterRecoveryConfiguration)
  spec.csharp:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    nameWithType: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    nameWithType: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: IList`1
  isExternal: true
  name: IList<>
  nameWithType: IList<>
  fullName: IList<>
  nameWithType.vb: IList(Of )
  fullname.vb: IList(Of )
  name.vb: IList(Of )
  spec.csharp:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.#ctor
  isExternal: false
  name: ServerDisasterRecoveryConfigurationListResponse
  nameWithType: ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurationListResponse
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.ServerDisasterRecoveryConfigurationListResponse
- uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator*
  commentId: Overload:Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
  isExternal: false
  name: GetEnumerator
  nameWithType: ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
  fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfigurationListResponse.GetEnumerator
- uid: IEnumerator{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}
  commentId: '!:IEnumerator{Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration}'
  definition: IEnumerator`1
  name: IEnumerator<ServerDisasterRecoveryConfiguration>
  nameWithType: IEnumerator<ServerDisasterRecoveryConfiguration>
  fullName: IEnumerator<Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration>
  nameWithType.vb: IEnumerator(Of ServerDisasterRecoveryConfiguration)
  fullname.vb: IEnumerator(Of Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration)
  name.vb: IEnumerator(Of ServerDisasterRecoveryConfiguration)
  spec.csharp:
  - uid: IEnumerator`1
    name: IEnumerator
    nameWithType: IEnumerator
    fullName: IEnumerator
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    nameWithType: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerator`1
    name: IEnumerator
    nameWithType: IEnumerator
    fullName: IEnumerator
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
    name: ServerDisasterRecoveryConfiguration
    nameWithType: ServerDisasterRecoveryConfiguration
    fullName: Microsoft.Azure.Management.Sql.Models.ServerDisasterRecoveryConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: IEnumerator`1
  isExternal: true
  name: IEnumerator<>
  nameWithType: IEnumerator<>
  fullName: IEnumerator<>
  nameWithType.vb: IEnumerator(Of )
  fullname.vb: IEnumerator(Of )
  name.vb: IEnumerator(Of )
  spec.csharp:
  - uid: IEnumerator`1
    name: IEnumerator
    nameWithType: IEnumerator
    fullName: IEnumerator
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerator`1
    name: IEnumerator
    nameWithType: IEnumerator
    fullName: IEnumerator
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
