### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  commentId: T:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  id: RDPSettingsParameters
  parent: Microsoft.Azure.Management.HDInsight.Models
  children:
  - Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor
  - Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor(Microsoft.Azure.Management.HDInsight.Models.OsProfile)
  - Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  langs:
  - csharp
  - vb
  name: RDPSettingsParameters
  nameWithType: RDPSettingsParameters
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  type: Class
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
      commit: 84e4b02dd0a9dc2fd137923ac43dc53945b54097
    id: RDPSettingsParameters
    path: src/azure-sdk-for-net-master/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nParameters specifying the data factory gateway definition for a create\nor update operation.\n"
  example: []
  syntax:
    content: 'public class RDPSettingsParameters : object'
    content.vb: >-
      Public Class RDPSettingsParameters
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  id: OsProfile
  parent: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  langs:
  - csharp
  - vb
  name: OsProfile
  nameWithType: RDPSettingsParameters.OsProfile
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  type: Property
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
      commit: 84e4b02dd0a9dc2fd137923ac43dc53945b54097
    id: OsProfile
    path: src/azure-sdk-for-net-master/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nRequired. Gets or sets the definition of a data factory gateway to\nbe created or updated.\n"
  example: []
  syntax:
    content: public OsProfile OsProfile { get; set; }
    content.vb: Public Property OsProfile As OsProfile
    parameters: []
    return:
      type: Microsoft.Azure.Management.HDInsight.Models.OsProfile
  overload: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor
  commentId: M:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  langs:
  - csharp
  - vb
  name: RDPSettingsParameters()
  nameWithType: RDPSettingsParameters.RDPSettingsParameters()
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.RDPSettingsParameters()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
      commit: 84e4b02dd0a9dc2fd137923ac43dc53945b54097
    id: .ctor
    path: src/azure-sdk-for-net-master/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nInitializes a new instance of the RDPSettingsParameters class.\n"
  example: []
  syntax:
    content: public RDPSettingsParameters()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor(Microsoft.Azure.Management.HDInsight.Models.OsProfile)
  commentId: M:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor(Microsoft.Azure.Management.HDInsight.Models.OsProfile)
  id: '#ctor(Microsoft.Azure.Management.HDInsight.Models.OsProfile)'
  parent: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters
  langs:
  - csharp
  - vb
  name: RDPSettingsParameters(OsProfile)
  nameWithType: RDPSettingsParameters.RDPSettingsParameters(OsProfile)
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.RDPSettingsParameters(Microsoft.Azure.Management.HDInsight.Models.OsProfile)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
      commit: 84e4b02dd0a9dc2fd137923ac43dc53945b54097
    id: .ctor
    path: src/azure-sdk-for-net-master/src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RDPSettingsParameters.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nInitializes a new instance of the RDPSettingsParameters class with\nrequired arguments.\n"
  example: []
  syntax:
    content: public RDPSettingsParameters(OsProfile osProfile)
    content.vb: Public Sub New(osProfile As OsProfile)
    parameters:
    - id: osProfile
      type: Microsoft.Azure.Management.HDInsight.Models.OsProfile
  overload: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.HDInsight.Models
  commentId: N:Microsoft.Azure.Management.HDInsight.Models
  isExternal: false
  name: Microsoft.Azure.Management.HDInsight.Models
  nameWithType: Microsoft.Azure.Management.HDInsight.Models
  fullName: Microsoft.Azure.Management.HDInsight.Models
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile*
  commentId: Overload:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
  isExternal: false
  name: OsProfile
  nameWithType: RDPSettingsParameters.OsProfile
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.OsProfile
- uid: Microsoft.Azure.Management.HDInsight.Models.OsProfile
  commentId: T:Microsoft.Azure.Management.HDInsight.Models.OsProfile
  parent: Microsoft.Azure.Management.HDInsight.Models
  isExternal: false
  name: OsProfile
  nameWithType: OsProfile
  fullName: Microsoft.Azure.Management.HDInsight.Models.OsProfile
- uid: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor*
  commentId: Overload:Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.#ctor
  isExternal: false
  name: RDPSettingsParameters
  nameWithType: RDPSettingsParameters.RDPSettingsParameters
  fullName: Microsoft.Azure.Management.HDInsight.Models.RDPSettingsParameters.RDPSettingsParameters
