### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings
  commentId: T:Microsoft.Azure.Management.HDInsight.Models.RdpSettings
  id: RdpSettings
  parent: Microsoft.Azure.Management.HDInsight.Models
  children:
  - Microsoft.Azure.Management.HDInsight.Models.RdpSettings.#ctor
  - Microsoft.Azure.Management.HDInsight.Models.RdpSettings.ExpiryDate
  - Microsoft.Azure.Management.HDInsight.Models.RdpSettings.Password
  - Microsoft.Azure.Management.HDInsight.Models.RdpSettings.UserName
  langs:
  - csharp
  - vb
  name: RdpSettings
  nameWithType: RdpSettings
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings
  type: Class
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: RdpSettings
    path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
    startLine: 26
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  syntax:
    content: 'public class RdpSettings : object'
    content.vb: >-
      Public Class RdpSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.ExpiryDate
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.RdpSettings.ExpiryDate
  id: ExpiryDate
  parent: Microsoft.Azure.Management.HDInsight.Models.RdpSettings
  langs:
  - csharp
  - vb
  name: ExpiryDate
  nameWithType: RdpSettings.ExpiryDate
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.ExpiryDate
  type: Property
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ExpiryDate
    path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nOptional. Gets or sets the RDP expiry date.\n"
  example: []
  syntax:
    content: public DateTime ExpiryDate { get; set; }
    content.vb: Public Property ExpiryDate As DateTime
    parameters: []
    return:
      type: DateTime
  overload: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.ExpiryDate*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.Password
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.RdpSettings.Password
  id: Password
  parent: Microsoft.Azure.Management.HDInsight.Models.RdpSettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: RdpSettings.Password
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.Password
  type: Property
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Password
    path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
    startLine: 44
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nOptional. Gets or sets the password for the RDP user.\n"
  example: []
  syntax:
    content: public string Password { get; set; }
    content.vb: Public Property Password As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.Password*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.UserName
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.RdpSettings.UserName
  id: UserName
  parent: Microsoft.Azure.Management.HDInsight.Models.RdpSettings
  langs:
  - csharp
  - vb
  name: UserName
  nameWithType: RdpSettings.UserName
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.UserName
  type: Property
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: UserName
    path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
    startLine: 55
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nOptional. Gets or sets the username for the RDP user.\n"
  example: []
  syntax:
    content: public string UserName { get; set; }
    content.vb: Public Property UserName As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.UserName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.#ctor
  commentId: M:Microsoft.Azure.Management.HDInsight.Models.RdpSettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.HDInsight.Models.RdpSettings
  langs:
  - csharp
  - vb
  name: RdpSettings()
  nameWithType: RdpSettings.RdpSettings()
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.RdpSettings()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/RdpSettings.cs
    startLine: 64
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nInitializes a new instance of the RdpSettings class.\n"
  example: []
  syntax:
    content: public RdpSettings()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.HDInsight.Models
  commentId: N:Microsoft.Azure.Management.HDInsight.Models
  isExternal: false
  name: Microsoft.Azure.Management.HDInsight.Models
  nameWithType: Microsoft.Azure.Management.HDInsight.Models
  fullName: Microsoft.Azure.Management.HDInsight.Models
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.ExpiryDate*
  commentId: Overload:Microsoft.Azure.Management.HDInsight.Models.RdpSettings.ExpiryDate
  isExternal: false
  name: ExpiryDate
  nameWithType: RdpSettings.ExpiryDate
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.ExpiryDate
- uid: DateTime
  isExternal: true
  name: DateTime
  nameWithType: DateTime
  fullName: DateTime
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.Password*
  commentId: Overload:Microsoft.Azure.Management.HDInsight.Models.RdpSettings.Password
  isExternal: false
  name: Password
  nameWithType: RdpSettings.Password
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.Password
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.UserName*
  commentId: Overload:Microsoft.Azure.Management.HDInsight.Models.RdpSettings.UserName
  isExternal: false
  name: UserName
  nameWithType: RdpSettings.UserName
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.UserName
- uid: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.#ctor*
  commentId: Overload:Microsoft.Azure.Management.HDInsight.Models.RdpSettings.#ctor
  isExternal: false
  name: RdpSettings
  nameWithType: RdpSettings.RdpSettings
  fullName: Microsoft.Azure.Management.HDInsight.Models.RdpSettings.RdpSettings
