### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  commentId: T:Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  id: ClusterConfigurationsResponse
  parent: Microsoft.Azure.Management.HDInsight.Models
  children:
  - Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor
  - Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  langs:
  - csharp
  - vb
  name: ClusterConfigurationsResponse
  nameWithType: ClusterConfigurationsResponse
  fullName: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ClusterConfigurationsResponse
    path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nThe Cluster Configurations operation response.\n"
  example: []
  syntax:
    content: 'public class ClusterConfigurationsResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ClusterConfigurationsResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  commentId: P:Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  id: Configuration
  parent: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: ClusterConfigurationsResponse.Configuration
  fullName: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  type: Property
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Configuration
    path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nOptional.\n"
  example: []
  syntax:
    content: public IDictionary<string, string> Configuration { get; set; }
    content.vb: Public Property Configuration As IDictionary(Of String, String)
    parameters: []
    return:
      type: IDictionary{System.String,System.String}
  overload: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor
  commentId: M:Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse
  langs:
  - csharp
  - vb
  name: ClusterConfigurationsResponse()
  nameWithType: ClusterConfigurationsResponse.ClusterConfigurationsResponse()
  fullName: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.ClusterConfigurationsResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/HDInsight/HDInsight/Generated/Models/ClusterConfigurationsResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.HDInsight
  namespace: Microsoft.Azure.Management.HDInsight.Models
  summary: "\nInitializes a new instance of the ClusterConfigurationsResponse\nclass.\n"
  example: []
  syntax:
    content: public ClusterConfigurationsResponse()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.HDInsight.Models
  commentId: N:Microsoft.Azure.Management.HDInsight.Models
  isExternal: false
  name: Microsoft.Azure.Management.HDInsight.Models
  nameWithType: Microsoft.Azure.Management.HDInsight.Models
  fullName: Microsoft.Azure.Management.HDInsight.Models
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration*
  commentId: Overload:Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
  isExternal: false
  name: Configuration
  nameWithType: ClusterConfigurationsResponse.Configuration
  fullName: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.Configuration
- uid: IDictionary{System.String,System.String}
  commentId: '!:IDictionary{System.String,System.String}'
  definition: IDictionary`2
  name: IDictionary<String, String>
  nameWithType: IDictionary<String, String>
  fullName: IDictionary<System.String, System.String>
  nameWithType.vb: IDictionary(Of String, String)
  fullname.vb: IDictionary(Of System.String, System.String)
  name.vb: IDictionary(Of String, String)
  spec.csharp:
  - uid: IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: IDictionary`2
  isExternal: true
  name: IDictionary<, >
  nameWithType: IDictionary<, >
  fullName: IDictionary<, >
  nameWithType.vb: IDictionary(Of , )
  fullname.vb: IDictionary(Of , )
  name.vb: IDictionary(Of , )
  spec.csharp:
  - uid: IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor*
  commentId: Overload:Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.#ctor
  isExternal: false
  name: ClusterConfigurationsResponse
  nameWithType: ClusterConfigurationsResponse.ClusterConfigurationsResponse
  fullName: Microsoft.Azure.Management.HDInsight.Models.ClusterConfigurationsResponse.ClusterConfigurationsResponse
