### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  id: ITelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: ITelemetryInitializer
  nameWithType: ITelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  type: Interface
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/ITelemetryInitializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ITelemetryInitializer
    path: src/Core/Managed/Shared/Extensibility/ITelemetryInitializer.cs
    startLine: 12
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nRepresents an object that initializes <xref href=\"Microsoft.ApplicationInsights.Channel.ITelemetry\" data-throw-if-not-resolved=\"false\"></xref> objects.\n"
  remarks: "\nThe <xref href=\"Microsoft.ApplicationInsights.DataContracts.TelemetryContext\" data-throw-if-not-resolved=\"false\"></xref> instances use <xref href=\"Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer\" data-throw-if-not-resolved=\"false\"></xref> objects to \nautomatically initialize properties of the <xref href=\"Microsoft.ApplicationInsights.Channel.ITelemetry\" data-throw-if-not-resolved=\"false\"></xref> objects.\n"
  example: []
  syntax:
    content: public interface ITelemetryInitializer
    content.vb: Public Interface ITelemetryInitializer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  langs:
  - csharp
  - vb
  name: Initialize(ITelemetry)
  nameWithType: ITelemetryInitializer.Initialize(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/ITelemetryInitializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Initialize
    path: src/Core/Managed/Shared/Extensibility/ITelemetryInitializer.cs
    startLine: 17
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nInitializes properties of the specified <xref href=\"Microsoft.ApplicationInsights.Channel.ITelemetry\" data-throw-if-not-resolved=\"false\"></xref> object.\n"
  example: []
  syntax:
    content: void Initialize(ITelemetry telemetry)
    content.vb: Sub Initialize(telemetry As ITelemetry)
    parameters:
    - id: telemetry
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
  overload: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize*
references:
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  nameWithType: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  commentId: T:Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: TelemetryContext
  nameWithType: TelemetryContext
  fullName: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: ITelemetryInitializer
  nameWithType: ITelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  nameWithType: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize
  isExternal: false
  name: Initialize
  nameWithType: ITelemetryInitializer.Initialize
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize
