### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  id: IOperationHolder`1
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry
  langs:
  - csharp
  - vb
  name: IOperationHolder<T>
  nameWithType: IOperationHolder<T>
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>
  type: Interface
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/IOperationHolder.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: IOperationHolder
    path: src/Core/Managed/Shared/Extensibility/IOperationHolder.cs
    startLine: 8
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nRepresents the operation item that holds telemetry which is tracked on end request. Operation can be associated with either WEB or SQL dependencies.\n"
  example: []
  syntax:
    content: 'public interface IOperationHolder<T> : IDisposable'
    content.vb: >-
      Public Interface IOperationHolder(Of T)
          Inherits IDisposable
    typeParameters:
    - id: T
  inheritedMembers:
  - System.IDisposable.Dispose
  nameWithType.vb: IOperationHolder(Of T)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T)
  name.vb: IOperationHolder(Of T)
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry
  commentId: P:Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry
  id: Telemetry
  parent: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  langs:
  - csharp
  - vb
  name: Telemetry
  nameWithType: IOperationHolder<T>.Telemetry
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>.Telemetry
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/IOperationHolder.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Telemetry
    path: src/Core/Managed/Shared/Extensibility/IOperationHolder.cs
    startLine: 13
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nGets Telemetry item of interest that is created when StartOperation function of ClientExtensions is invoked.\n"
  example: []
  syntax:
    content: T Telemetry { get; }
    content.vb: ReadOnly Property Telemetry As T
    parameters: []
    return:
      type: '{T}'
  overload: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry*
  nameWithType.vb: IOperationHolder(Of T).Telemetry
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T).Telemetry
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    nameWithType: IDisposable.Dispose
    fullName: System.IDisposable.Dispose
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    nameWithType: IDisposable.Dispose
    fullName: System.IDisposable.Dispose
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1.Telemetry
  isExternal: false
  name: Telemetry
  nameWithType: IOperationHolder<T>.Telemetry
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>.Telemetry
  nameWithType.vb: IOperationHolder(Of T).Telemetry
  fullname.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T).Telemetry
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  isExternal: false
  name: T
  nameWithType: T
  fullName: T
