### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  commentId: T:Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  id: ISupportSampling
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  langs:
  - csharp
  - vb
  name: ISupportSampling
  nameWithType: ISupportSampling
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  type: Interface
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/ISupportSampling.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ISupportSampling
    path: src/Core/Managed/Shared/DataContracts/ISupportSampling.cs
    startLine: 5
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nRepresent objects that support data sampling.\n"
  example: []
  syntax:
    content: public interface ISupportSampling
    content.vb: Public Interface ISupportSampling
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  commentId: P:Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  id: SamplingPercentage
  parent: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  langs:
  - csharp
  - vb
  name: SamplingPercentage
  nameWithType: ISupportSampling.SamplingPercentage
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/ISupportSampling.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: SamplingPercentage
    path: src/Core/Managed/Shared/DataContracts/ISupportSampling.cs
    startLine: 10
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nGets or sets data sampling percentage (between 0 and 100).\n"
  example: []
  syntax:
    content: double ? SamplingPercentage { get; set; }
    content.vb: Property SamplingPercentage As Double?
    parameters: []
    return:
      type: System.Nullable{System.Double}
  overload: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage*
  modifiers.csharp:
  - get
  - set
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage*
  commentId: Overload:Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
  isExternal: false
  name: SamplingPercentage
  nameWithType: ISupportSampling.SamplingPercentage
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling.SamplingPercentage
- uid: System.Nullable{System.Double}
  commentId: T:System.Nullable{System.Double}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Double>
  nameWithType: Nullable<Double>
  fullName: System.Nullable<System.Double>
  nameWithType.vb: Nullable(Of Double)
  fullname.vb: System.Nullable(Of System.Double)
  name.vb: Nullable(Of Double)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Double
    name: Double
    nameWithType: Double
    fullName: System.Double
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Double
    name: Double
    nameWithType: Double
    fullName: System.Double
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
