### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.DataContracts.SessionState
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SessionState
  id: SessionState
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.SessionState.End
  - Microsoft.ApplicationInsights.DataContracts.SessionState.Start
  langs:
  - csharp
  - vb
  name: SessionState
  nameWithType: SessionState
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionState
  type: Enum
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionState.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: SessionState
    path: src/Core/Managed/Shared/DataContracts/SessionState.cs
    startLine: 7
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nContains values that identify state of a user session.\n"
  example: []
  syntax:
    content: >-
      [Obsolete("Session state events are no longer used.")]

      public enum SessionState
    content.vb: >-
      <Obsolete("Session state events are no longer used.")>

      Public Enum SessionState
  attributes:
  - type: System.ObsoleteAttribute
    ctor: System.ObsoleteAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Session state events are no longer used.
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.ApplicationInsights.DataContracts.SessionState.Start
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SessionState.Start
  id: Start
  parent: Microsoft.ApplicationInsights.DataContracts.SessionState
  langs:
  - csharp
  - vb
  name: Start
  nameWithType: SessionState.Start
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionState.Start
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionState.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Start
    path: src/Core/Managed/Shared/DataContracts/SessionState.cs
    startLine: 13
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nIndicates that a user session started.\n"
  example: []
  syntax:
    content: Start = 0
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SessionState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.ApplicationInsights.DataContracts.SessionState.End
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SessionState.End
  id: End
  parent: Microsoft.ApplicationInsights.DataContracts.SessionState
  langs:
  - csharp
  - vb
  name: End
  nameWithType: SessionState.End
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionState.End
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionState.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: End
    path: src/Core/Managed/Shared/DataContracts/SessionState.cs
    startLine: 18
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nIndicates that a user session ended.\n"
  example: []
  syntax:
    content: End = 1
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SessionState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
- uid: Microsoft.ApplicationInsights.DataContracts.SessionState
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SessionState
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: SessionState
  nameWithType: SessionState
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionState
