### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  id: SeverityLevel
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Critical
  - Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Error
  - Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Information
  - Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Verbose
  - Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Warning
  langs:
  - csharp
  - vb
  name: SeverityLevel
  nameWithType: SeverityLevel
  fullName: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  type: Enum
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: SeverityLevel
    path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
    startLine: 5
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nThis enumeration is used by ExceptionTelemetry and TraceTelemetry to identify severity level.\n"
  example: []
  syntax:
    content: public enum SeverityLevel
    content.vb: Public Enum SeverityLevel
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Verbose
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Verbose
  id: Verbose
  parent: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  langs:
  - csharp
  - vb
  name: Verbose
  nameWithType: SeverityLevel.Verbose
  fullName: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Verbose
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Verbose
    path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
    startLine: 10
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nVerbose severity level.\n"
  example: []
  syntax:
    content: Verbose = 0
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Information
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Information
  id: Information
  parent: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  langs:
  - csharp
  - vb
  name: Information
  nameWithType: SeverityLevel.Information
  fullName: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Information
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Information
    path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
    startLine: 15
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nInformation severity level.\n"
  example: []
  syntax:
    content: Information = 1
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Warning
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Warning
  id: Warning
  parent: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  langs:
  - csharp
  - vb
  name: Warning
  nameWithType: SeverityLevel.Warning
  fullName: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Warning
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Warning
    path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
    startLine: 20
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nWarning severity level.\n"
  example: []
  syntax:
    content: Warning = 2
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Error
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Error
  id: Error
  parent: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  langs:
  - csharp
  - vb
  name: Error
  nameWithType: SeverityLevel.Error
  fullName: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Error
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Error
    path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
    startLine: 25
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nError severity level.\n"
  example: []
  syntax:
    content: Error = 3
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Critical
  commentId: F:Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Critical
  id: Critical
  parent: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  langs:
  - csharp
  - vb
  name: Critical
  nameWithType: SeverityLevel.Critical
  fullName: Microsoft.ApplicationInsights.DataContracts.SeverityLevel.Critical
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Critical
    path: src/Core/Managed/Shared/DataContracts/SeverityLevel.cs
    startLine: 30
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nCritical severity level.\n"
  example: []
  syntax:
    content: Critical = 4
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
- uid: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: SeverityLevel
  nameWithType: SeverityLevel
  fullName: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
