### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetry
  id: ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  children:
  - Microsoft.ApplicationInsights.Channel.ITelemetry.Context
  - Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
  - Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
  - Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
  langs:
  - csharp
  - vb
  name: ITelemetry
  nameWithType: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
  type: Interface
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ITelemetry
    path: src/Core/Managed/Shared/Channel/ITelemetry.cs
    startLine: 8
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nThe base telemetry type for application insights.\n"
  example: []
  syntax:
    content: public interface ITelemetry
    content.vb: Public Interface ITelemetry
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
  commentId: P:Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
  id: Timestamp
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  langs:
  - csharp
  - vb
  name: Timestamp
  nameWithType: ITelemetry.Timestamp
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Timestamp
    path: src/Core/Managed/Shared/Channel/ITelemetry.cs
    startLine: 13
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nGets or sets date and time when telemetry was recorded.\n"
  example: []
  syntax:
    content: DateTimeOffset Timestamp { get; set; }
    content.vb: Property Timestamp As DateTimeOffset
    parameters: []
    return:
      type: System.DateTimeOffset
  overload: Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp*
  modifiers.csharp:
  - get
  - set
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Context
  commentId: P:Microsoft.ApplicationInsights.Channel.ITelemetry.Context
  id: Context
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  langs:
  - csharp
  - vb
  name: Context
  nameWithType: ITelemetry.Context
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Context
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Context
    path: src/Core/Managed/Shared/Channel/ITelemetry.cs
    startLine: 18
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nGets the context associated with this telemetry instance.\n"
  example: []
  syntax:
    content: TelemetryContext Context { get; }
    content.vb: ReadOnly Property Context As TelemetryContext
    parameters: []
    return:
      type: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  overload: Microsoft.ApplicationInsights.Channel.ITelemetry.Context*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
  commentId: P:Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
  id: Sequence
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  langs:
  - csharp
  - vb
  name: Sequence
  nameWithType: ITelemetry.Sequence
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Sequence
    path: src/Core/Managed/Shared/Channel/ITelemetry.cs
    startLine: 32
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nGets or sets the value that defines absolute order of the telemetry item.\n"
  remarks: "\nThe sequence is used to track absolute order of uploaded telemetry items. It is a two-part value that includes \na stable identifier for the current boot session and an incrementing identifier for each event added to the upload queue:\nFor UTC this would increment for all events across the system.\nFor Persistence this would increment for all events emitted from the hosting process.    \nThe Sequence helps track how many events were fired and how many events were uploaded and enables identification \nof data lost during upload and de-duplication of events on the ingress server.\nFrom <a href=\"https://microsoft.sharepoint.com/teams/CommonSchema/Shared%20Documents/Schema%20Specs/Common%20Schema%202%20-%20Language%20Specification.docx\"></a>.\n"
  example: []
  syntax:
    content: string Sequence { get; set; }
    content.vb: Property Sequence As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence*
  modifiers.csharp:
  - get
  - set
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
  commentId: M:Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
  id: Sanitize
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  langs:
  - csharp
  - vb
  name: Sanitize()
  nameWithType: ITelemetry.Sanitize()
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize()
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Sanitize
    path: src/Core/Managed/Shared/Channel/ITelemetry.cs
    startLine: 37
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nSanitizes the properties of the telemetry item based on DP constraints.\n"
  example: []
  syntax:
    content: void Sanitize()
    content.vb: Sub Sanitize
  overload: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize*
references:
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  nameWithType: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp*
  commentId: Overload:Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
  isExternal: false
  name: Timestamp
  nameWithType: ITelemetry.Timestamp
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
- uid: System.DateTimeOffset
  commentId: T:System.DateTimeOffset
  parent: System
  isExternal: true
  name: DateTimeOffset
  nameWithType: DateTimeOffset
  fullName: System.DateTimeOffset
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Context*
  commentId: Overload:Microsoft.ApplicationInsights.Channel.ITelemetry.Context
  isExternal: false
  name: Context
  nameWithType: ITelemetry.Context
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Context
- uid: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  commentId: T:Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: TelemetryContext
  nameWithType: TelemetryContext
  fullName: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence*
  commentId: Overload:Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
  isExternal: false
  name: Sequence
  nameWithType: ITelemetry.Sequence
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize*
  commentId: Overload:Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
  isExternal: false
  name: Sanitize
  nameWithType: ITelemetry.Sanitize
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
