### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  commentId: T:Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  id: ExceptionHandledAt
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.Platform
  - Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.Unhandled
  - Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.UserCode
  langs:
  - csharp
  - vb
  name: ExceptionHandledAt
  nameWithType: ExceptionHandledAt
  fullName: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  type: Enum
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/ExceptionHandledAt.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ExceptionHandledAt
    path: src/Core/Managed/Shared/DataContracts/ExceptionHandledAt.cs
    startLine: 7
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nThis enumeration is used by ExceptionTelemetry to identify if and where exception was handled.\n"
  example: []
  syntax:
    content: >-
      [Obsolete("Use custom properties to report exception handling layer")]

      public enum ExceptionHandledAt
    content.vb: >-
      <Obsolete("Use custom properties to report exception handling layer")>

      Public Enum ExceptionHandledAt
  attributes:
  - type: System.ObsoleteAttribute
    ctor: System.ObsoleteAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Use custom properties to report exception handling layer
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.Unhandled
  commentId: F:Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.Unhandled
  id: Unhandled
  parent: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  langs:
  - csharp
  - vb
  name: Unhandled
  nameWithType: ExceptionHandledAt.Unhandled
  fullName: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.Unhandled
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/ExceptionHandledAt.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Unhandled
    path: src/Core/Managed/Shared/DataContracts/ExceptionHandledAt.cs
    startLine: 13
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nException was not handled. Application crashed.\n"
  example: []
  syntax:
    content: Unhandled = 0
    return:
      type: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.UserCode
  commentId: F:Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.UserCode
  id: UserCode
  parent: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  langs:
  - csharp
  - vb
  name: UserCode
  nameWithType: ExceptionHandledAt.UserCode
  fullName: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.UserCode
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/ExceptionHandledAt.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: UserCode
    path: src/Core/Managed/Shared/DataContracts/ExceptionHandledAt.cs
    startLine: 18
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nException was handled in user code.\n"
  example: []
  syntax:
    content: UserCode = 1
    return:
      type: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.Platform
  commentId: F:Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.Platform
  id: Platform
  parent: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  langs:
  - csharp
  - vb
  name: Platform
  nameWithType: ExceptionHandledAt.Platform
  fullName: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt.Platform
  type: Field
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/ExceptionHandledAt.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Platform
    path: src/Core/Managed/Shared/DataContracts/ExceptionHandledAt.cs
    startLine: 23
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nException was handled by some platform handlers.\n"
  example: []
  syntax:
    content: Platform = 2
    return:
      type: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
- uid: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  commentId: T:Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: ExceptionHandledAt
  nameWithType: ExceptionHandledAt
  fullName: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
