### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  id: ITelemetryChannel
  parent: Microsoft.ApplicationInsights.Channel
  children:
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: ITelemetryChannel
  nameWithType: ITelemetryChannel
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  type: Interface
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ITelemetryChannel
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 12
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nRepresents a communication channel for sending telemetry to application insights.\n"
  example: []
  syntax:
    content: 'public interface ITelemetryChannel : IDisposable'
    content.vb: >-
      Public Interface ITelemetryChannel
          Inherits IDisposable
  inheritedMembers:
  - System.IDisposable.Dispose
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  commentId: P:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  id: DeveloperMode
  parent: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  langs:
  - csharp
  - vb
  name: DeveloperMode
  nameWithType: ITelemetryChannel.DeveloperMode
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: DeveloperMode
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 17
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nGets or sets a value indicating whether this channel is in developer mode.\n"
  example: []
  syntax:
    content: bool ? DeveloperMode { get; set; }
    content.vb: Property DeveloperMode As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  overload: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode*
  modifiers.csharp:
  - get
  - set
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  commentId: P:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  id: EndpointAddress
  parent: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  langs:
  - csharp
  - vb
  name: EndpointAddress
  nameWithType: ITelemetryChannel.EndpointAddress
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: EndpointAddress
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 22
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nGets or sets the endpoint address of the channel.\n"
  example: []
  syntax:
    content: string EndpointAddress { get; set; }
    content.vb: Property EndpointAddress As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress*
  modifiers.csharp:
  - get
  - set
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  langs:
  - csharp
  - vb
  name: Send(ITelemetry)
  nameWithType: ITelemetryChannel.Send(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Send
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 27
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nSends an instance of ITelemetry through the channel.\n"
  example: []
  syntax:
    content: void Send(ITelemetry item)
    content.vb: Sub Send(item As ITelemetry)
    parameters:
    - id: item
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
  overload: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send*
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush
  commentId: M:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush
  id: Flush
  parent: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  langs:
  - csharp
  - vb
  name: Flush()
  nameWithType: ITelemetryChannel.Flush()
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush()
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Flush
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 32
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nFlushes the in-memory buffer.\n"
  example: []
  syntax:
    content: void Flush()
    content.vb: Sub Flush
  overload: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush*
references:
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  nameWithType: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    nameWithType: IDisposable.Dispose
    fullName: System.IDisposable.Dispose
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    nameWithType: IDisposable.Dispose
    fullName: System.IDisposable.Dispose
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode*
  commentId: Overload:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  isExternal: false
  name: DeveloperMode
  nameWithType: ITelemetryChannel.DeveloperMode
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  nameWithType: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  nameWithType.vb: Nullable(Of Boolean)
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress*
  commentId: Overload:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  isExternal: false
  name: EndpointAddress
  nameWithType: ITelemetryChannel.EndpointAddress
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send*
  commentId: Overload:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send
  isExternal: false
  name: Send
  nameWithType: ITelemetryChannel.Send
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  nameWithType: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush*
  commentId: Overload:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush
  isExternal: false
  name: Flush
  nameWithType: ITelemetryChannel.Flush
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush
