### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  commentId: T:Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  id: ITelemetryProcessor
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: ITelemetryProcessor
  nameWithType: ITelemetryProcessor
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  type: Interface
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/ITelemetryProcessor.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
      commit: 309ff76563b7db90cb26c049f9c671c5a61fb8dd
    id: ITelemetryProcessor
    path: src/ApplicationInsights-dotnet/src/Core/Managed/Shared/Extensibility/ITelemetryProcessor.cs
    startLine: 7
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nRepresents an object used to process telemetry as part of sending it to Application Insights.\n"
  example: []
  syntax:
    content: public interface ITelemetryProcessor
    content.vb: Public Interface ITelemetryProcessor
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  langs:
  - csharp
  - vb
  name: Process(ITelemetry)
  nameWithType: ITelemetryProcessor.Process(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/ITelemetryProcessor.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
      commit: 309ff76563b7db90cb26c049f9c671c5a61fb8dd
    id: Process
    path: src/ApplicationInsights-dotnet/src/Core/Managed/Shared/Extensibility/ITelemetryProcessor.cs
    startLine: 13
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nProcess a collected telemetry item.\n"
  example: []
  syntax:
    content: void Process(ITelemetry item)
    content.vb: Sub Process(item As ITelemetry)
    parameters:
    - id: item
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
      description: A collected Telemetry item.
  overload: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process*
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process
  isExternal: false
  name: Process
  nameWithType: ITelemetryProcessor.Process
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor.Process
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  nameWithType: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  nameWithType: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
