### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  commentId: T:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  id: OperationStatusValues
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  children:
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Canceled
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Failed
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.InProgress
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Invalid
  - Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Succeeded
  langs:
  - csharp
  - vb
  name: OperationStatusValues
  nameWithType: OperationStatusValues
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
      commit: c575ec3380165f3988ddd6efb85d010882c4936e
    id: OperationStatusValues
    path: src/azure-sdk-for-net/src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
    startLine: 10
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  summary: "\nDefines values for OperationStatusValues.\n"
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof (StringEnumConverter))]

      public enum OperationStatusValues
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum OperationStatusValues
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Invalid
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Invalid
  id: Invalid
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: Invalid
  nameWithType: OperationStatusValues.Invalid
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Invalid
  type: Field
  source:
    remote:
      path: src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
      commit: c575ec3380165f3988ddd6efb85d010882c4936e
    id: Invalid
    path: src/azure-sdk-for-net/src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
    startLine: 13
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  syntax:
    content: >-
      [EnumMember(Value = "Invalid")]

      Invalid = 0
    content.vb: >-
      <EnumMember(Value:="Invalid")>

      Invalid = 0
    return:
      type: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Invalid
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.InProgress
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.InProgress
  id: InProgress
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: InProgress
  nameWithType: OperationStatusValues.InProgress
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.InProgress
  type: Field
  source:
    remote:
      path: src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
      commit: c575ec3380165f3988ddd6efb85d010882c4936e
    id: InProgress
    path: src/azure-sdk-for-net/src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  syntax:
    content: >-
      [EnumMember(Value = "InProgress")]

      InProgress = 1
    content.vb: >-
      <EnumMember(Value:="InProgress")>

      InProgress = 1
    return:
      type: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: InProgress
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Succeeded
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Succeeded
  id: Succeeded
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: Succeeded
  nameWithType: OperationStatusValues.Succeeded
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Succeeded
  type: Field
  source:
    remote:
      path: src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
      commit: c575ec3380165f3988ddd6efb85d010882c4936e
    id: Succeeded
    path: src/azure-sdk-for-net/src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  syntax:
    content: >-
      [EnumMember(Value = "Succeeded")]

      Succeeded = 2
    content.vb: >-
      <EnumMember(Value:="Succeeded")>

      Succeeded = 2
    return:
      type: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Succeeded
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Failed
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Failed
  id: Failed
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: Failed
  nameWithType: OperationStatusValues.Failed
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Failed
  type: Field
  source:
    remote:
      path: src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
      commit: c575ec3380165f3988ddd6efb85d010882c4936e
    id: Failed
    path: src/azure-sdk-for-net/src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
    startLine: 19
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  syntax:
    content: >-
      [EnumMember(Value = "Failed")]

      Failed = 3
    content.vb: >-
      <EnumMember(Value:="Failed")>

      Failed = 3
    return:
      type: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Failed
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Canceled
  commentId: F:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Canceled
  id: Canceled
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  langs:
  - csharp
  - vb
  name: Canceled
  nameWithType: OperationStatusValues.Canceled
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues.Canceled
  type: Field
  source:
    remote:
      path: src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
      commit: c575ec3380165f3988ddd6efb85d010882c4936e
    id: Canceled
    path: src/azure-sdk-for-net/src/ResourceManagement/RecoveryServices.Backup/Microsoft.Azure.Management.RecoveryServices.Backup/Generated/Models/OperationStatusValues.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.RecoveryServices.Backup
  namespace: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  syntax:
    content: >-
      [EnumMember(Value = "Canceled")]

      Canceled = 4
    content.vb: >-
      <EnumMember(Value:="Canceled")>

      Canceled = 4
    return:
      type: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Canceled
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  commentId: N:Microsoft.Azure.Management.RecoveryServices.Backup.Models
  isExternal: false
  name: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  nameWithType: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models
- uid: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  commentId: T:Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
  parent: Microsoft.Azure.Management.RecoveryServices.Backup.Models
  isExternal: false
  name: OperationStatusValues
  nameWithType: OperationStatusValues
  fullName: Microsoft.Azure.Management.RecoveryServices.Backup.Models.OperationStatusValues
