### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  id: DscConfigurationProvisioningState
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Succeeded
  langs:
  - csharp
  - vb
  name: DscConfigurationProvisioningState
  nameWithType: DscConfigurationProvisioningState
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProvisioningState.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DscConfigurationProvisioningState
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProvisioningState.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nProvisioning state of the configuration operation.\n"
  example: []
  syntax:
    content: public enum DscConfigurationProvisioningState
    content.vb: Public Enum DscConfigurationProvisioningState
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Succeeded
  commentId: F:Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Succeeded
  id: Succeeded
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  langs:
  - csharp
  - vb
  name: Succeeded
  nameWithType: DscConfigurationProvisioningState.Succeeded
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Succeeded
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProvisioningState.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Succeeded
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProvisioningState.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  syntax:
    content: Succeeded = 0
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationProvisioningState
  nameWithType: DscConfigurationProvisioningState
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
