### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  id: DscConfigurationParameter
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  langs:
  - csharp
  - vb
  name: DscConfigurationParameter
  nameWithType: DscConfigurationParameter
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DscConfigurationParameter
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nDefinition of the configuration parameter type.\n"
  example: []
  syntax:
    content: public class DscConfigurationParameter
    content.vb: Public Class DscConfigurationParameter
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  id: DefaultValue
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: DefaultValue
  nameWithType: DscConfigurationParameter.DefaultValue
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefaultValue
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the default value of parameter.\n"
  example: []
  syntax:
    content: public string DefaultValue { get; set; }
    content.vb: Public Property DefaultValue As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  id: IsMandatory
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: IsMandatory
  nameWithType: DscConfigurationParameter.IsMandatory
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IsMandatory
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets a Boolean value to indicate whether the\nparameter is madatory or not.\n"
  example: []
  syntax:
    content: public bool IsMandatory { get; set; }
    content.vb: Public Property IsMandatory As Boolean
    parameters: []
    return:
      type: System.Boolean
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  id: Position
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: Position
  nameWithType: DscConfigurationParameter.Position
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Position
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Get or sets the position of the parameter.\n"
  example: []
  syntax:
    content: public int Position { get; set; }
    content.vb: Public Property Position As Integer
    parameters: []
    return:
      type: System.Int32
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  id: Type
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: DscConfigurationParameter.Type
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Type
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the type of the parameter.\n"
  example: []
  syntax:
    content: public string Type { get; set; }
    content.vb: Public Property Type As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: DscConfigurationParameter()
  nameWithType: DscConfigurationParameter.DscConfigurationParameter()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DscConfigurationParameter()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 79
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscConfigurationParameter class.\n"
  example: []
  syntax:
    content: public DscConfigurationParameter()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  isExternal: false
  name: DefaultValue
  nameWithType: DscConfigurationParameter.DefaultValue
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  isExternal: false
  name: IsMandatory
  nameWithType: DscConfigurationParameter.IsMandatory
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  isExternal: false
  name: Position
  nameWithType: DscConfigurationParameter.Position
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  isExternal: false
  name: Type
  nameWithType: DscConfigurationParameter.Type
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor
  isExternal: false
  name: DscConfigurationParameter
  nameWithType: DscConfigurationParameter.DscConfigurationParameter
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DscConfigurationParameter
