### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfiguration
  id: DscConfiguration
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  langs:
  - csharp
  - vb
  name: DscConfiguration
  nameWithType: DscConfiguration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DscConfiguration
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nDefinition of the configuration type.\n"
  example: []
  syntax:
    content: 'public class DscConfiguration : ResourceBase'
    content.vb: >-
      Public Class DscConfiguration
          Inherits ResourceBase
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.ResourceBase
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Name
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  id: Properties
  parent: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: DscConfiguration.Properties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Properties
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the configuration properties.\n"
  example: []
  syntax:
    content: public DscConfigurationProperties Properties { get; set; }
    content.vb: Public Property Properties As DscConfigurationProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  overload: Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  langs:
  - csharp
  - vb
  name: DscConfiguration()
  nameWithType: DscConfiguration.DscConfiguration()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration.DscConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscConfiguration class.\n"
  example: []
  syntax:
    content: public DscConfiguration()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase
  commentId: T:Microsoft.Azure.Management.Automation.Models.ResourceBase
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: ResourceBase
  nameWithType: ResourceBase
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Etag
  nameWithType: ResourceBase.Etag
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Id
  nameWithType: ResourceBase.Id
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Location
  nameWithType: ResourceBase.Location
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Name
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceBase.Name
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Name
  nameWithType: ResourceBase.Name
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Name
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Tags
  nameWithType: ResourceBase.Tags
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Type
  nameWithType: ResourceBase.Type
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  isExternal: false
  name: Properties
  nameWithType: DscConfiguration.Properties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationProperties
  nameWithType: DscConfigurationProperties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor
  isExternal: false
  name: DscConfiguration
  nameWithType: DscConfiguration.DscConfiguration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration.DscConfiguration
