### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  id: DscConfigurationCreateOrUpdateParameters
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateParameters
  nameWithType: DscConfigurationCreateOrUpdateParameters
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DscConfigurationCreateOrUpdateParameters
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe parameters supplied to the create or update configuration operation.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationCreateOrUpdateParameters : ResourceCreateOrUpdateParameterBase'
    content.vb: >-
      Public Class DscConfigurationCreateOrUpdateParameters
          Inherits ResourceCreateOrUpdateParameterBase
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Location
  - Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Name
  - Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Tags
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  id: Properties
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: DscConfigurationCreateOrUpdateParameters.Properties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Properties
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nRequired. Gets or sets configuration create or update properties.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateProperties Properties { get; set; }
    content.vb: Public Property Properties As DscConfigurationCreateOrUpdateProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateParameters()
  nameWithType: DscConfigurationCreateOrUpdateParameters.DscConfigurationCreateOrUpdateParameters()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.DscConfigurationCreateOrUpdateParameters()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationCreateOrUpdateParameters class.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateParameters()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)
  id: '#ctor(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateParameters(DscConfigurationCreateOrUpdateProperties)
  nameWithType: DscConfigurationCreateOrUpdateParameters.DscConfigurationCreateOrUpdateParameters(DscConfigurationCreateOrUpdateProperties)
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.DscConfigurationCreateOrUpdateParameters(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationCreateOrUpdateParameters class with required\narguments.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateParameters(DscConfigurationCreateOrUpdateProperties properties)
    content.vb: Public Sub New(properties As DscConfigurationCreateOrUpdateProperties)
    parameters:
    - id: properties
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  commentId: T:Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: ResourceCreateOrUpdateParameterBase
  nameWithType: ResourceCreateOrUpdateParameterBase
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Location
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Location
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  isExternal: false
  name: Location
  nameWithType: ResourceCreateOrUpdateParameterBase.Location
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Location
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Name
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Name
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  isExternal: false
  name: Name
  nameWithType: ResourceCreateOrUpdateParameterBase.Name
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Name
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Tags
  commentId: P:Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Tags
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  isExternal: false
  name: Tags
  nameWithType: ResourceCreateOrUpdateParameterBase.Tags
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Tags
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  isExternal: false
  name: Properties
  nameWithType: DscConfigurationCreateOrUpdateParameters.Properties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationCreateOrUpdateProperties
  nameWithType: DscConfigurationCreateOrUpdateProperties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor
  isExternal: false
  name: DscConfigurationCreateOrUpdateParameters
  nameWithType: DscConfigurationCreateOrUpdateParameters.DscConfigurationCreateOrUpdateParameters
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.DscConfigurationCreateOrUpdateParameters
