### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  id: DeploymentChangeConfigurationMode
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  children:
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode.Auto
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode.Manual
  langs:
  - csharp
  - vb
  name: DeploymentChangeConfigurationMode
  nameWithType: DeploymentChangeConfigurationMode
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentChangeConfigurationMode.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DeploymentChangeConfigurationMode
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentChangeConfigurationMode.cs
    startLine: 26
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: public enum DeploymentChangeConfigurationMode
    content.vb: Public Enum DeploymentChangeConfigurationMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode.Auto
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode.Auto
  id: Auto
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  langs:
  - csharp
  - vb
  name: Auto
  nameWithType: DeploymentChangeConfigurationMode.Auto
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode.Auto
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentChangeConfigurationMode.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Auto
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentChangeConfigurationMode.cs
    startLine: 28
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Auto = 0
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode.Manual
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode.Manual
  id: Manual
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  langs:
  - csharp
  - vb
  name: Manual
  nameWithType: DeploymentChangeConfigurationMode.Manual
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode.Manual
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentChangeConfigurationMode.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Manual
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentChangeConfigurationMode.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Manual = 1
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.WindowsAzure.Management.Compute.Models
  commentId: N:Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Compute.Models
  nameWithType: Microsoft.WindowsAzure.Management.Compute.Models
  fullName: Microsoft.WindowsAzure.Management.Compute.Models
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: DeploymentChangeConfigurationMode
  nameWithType: DeploymentChangeConfigurationMode
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentChangeConfigurationMode
